### ISSUE TITLE
Renaming the repository name to libplanet (no trailing “.net”)?

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#105]
We do not have any plan to support or rewrite Libplanet in other languages than C# in the near future.  To be consistent with the names for branding, NuGet package, `namespace`, and so on, I suggest rename the repository also to planetarium/libplanet, no “.net” postfix.

**Comment by kijun** [comment]
agreed

**Comment by longfin** [comment]
Basically, I think that even if there are implementations in other languages / platforms, names that are not awkward are better.

But in reality

- As you said, we're not preparing implementations in other languages / platforms in near term.
- Even if other language / platform implementations are released, they will use names that are distinguishable from existing `Libplanet`. (e.g. `libplanet++`,  `libplanet-python`)

so I don't think that is a big problem.

**Comment by dahlia** [comment]
I'm going to rename the repository to planetarium/libplanet in 24 hours.

**Comment by dahlia** [comment]
Renamed the repository.  Redirection from existing links seems to work well, except of GitHub Pages: <https://planetarium.github.io/libplanet.net/>.  We should manually replace the links to the old name with <https://planetarium.github.io/libplanet/>.

**Comment by dahlia** [comment]
Give the docs new url: <https://docs.libplanet.io/>.
