### ISSUE TITLE
Turn Block<T>.Transactions into IReadOnlyList<Transaction<T>>

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1103]
Currencly `Block<T>.Transactions` property returns an `IEnumerable<Transaction<T>>`, but it's prone to realize the same contents multiple times.  In order to make its time complexity more predictable, I suggest to turn it into `IReadOnlyList<Transaction<T>>` instead.

**Comment by moreal** [comment]
It seems similar to #903. May not it be treated as one?

**Comment by dahlia** [comment]
@moreal Seems a dup.  I'm going to close this.
