### ISSUE TITLE
Change type of Peer.Urls to IPEndPoint

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#120]
We've chosen [`Uri`](https://docs.microsoft.com/en-US/dotnet/api/system.uri?view=netstandard-2.0) as element type of `Peer.Urls`  to represent peer's address. but `Uri` isn't appropriate type because it also contains information that we do not need. (e.g. path, protocol)

So, I suggest [`IPEndPoint`](https://docs.microsoft.com/en-US/dotnet/api/system.net.ipendpoint?view=netstandard-2.0) to peer's endpoint type.  it has only IP address and port.

**Comment by ipdae** [comment]
i'll try this issue.
