### ISSUE TITLE
Get rid of arbitrary `BlockChain<T>.Id` and refer chains (branches) by their tip hashes

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1232]
Currently every `BlockChain<T>` has its own arbitrary `Id` to refer a chain (branch).  However, as like Git does, chains (branches) can be referred by their tips, since their all ancestors including the genesis can be traced by going up along `Block<T>.PreviousHash`es until reaching the genesis.

This new approach has some advantages over the current approach:

- does not fork/swap chains, which take few seconds, to append blocks or reorg them; instead appoints a block as new tip
- no needs to “garbage-collect” unused chains, because garbage chains are never made at all
- no needs persistent indices, which take up disk linear in the number of blocks and the number of chains; instead records a single tip hash
- no needs to address other issues like #184

On the other hand, there are disadvantages as well:

- blocks cannot be random accessed by their indices; at least we need some heuristics or optimizations on that
- any other possibilities?

**Comment by kfangw** [comment]
I am totally agreed that the `chain id` is a redundant concept.

>no needs to “garbage-collect” unused chains, because garbage chains are never made at all
Is this approach assumes that the garbage is cleaned by the reorg process?

>no needs persistent indices, which take up disk linear in the number of blocks and the number of chains; instead records a single tip hash
It hasn't necessary. but, it would be helpful to get a block by a given block height

>blocks cannot be random accessed by their indices
If the index remains, it is not an issue.
