### ISSUE TITLE
Drop .NET Standard 2.0 support

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1266]
We've supported both .NET Standard 2.0 & 2.1, since [Unity](https://unity.com/) hadn't implemented .NET Standard 2.1, but only 2.0.  [However, Unity recently announced their fork of Mono now became to have .NET Standard 2.1 compatibility with full C# 8.][1]  If Unity became compliant with .NET Standard 2.1, we can drop .NET Standard 2.0 support with pleasure, and leave only .NET Standard 2.1 support.

[1]: https://forum.unity.com/threads/unity-future-net-development-status.1092205/#post-7032367

**Comment by dahlia** [comment]
If we can drop .NET Standard 2.0 support, we don't need to stick with C# 7.1 for unit tests anymore.

**Comment by TarogStar** [comment]
It seems that this cannot currently be implemented until the newer version of Unity is used, so this will need to wait.

**Comment by dahlia** [comment]
[Unity supports .NET Standard 2.1 since 2021.2.0b6](https://unity3d.com/unity/beta/2021.2.0b6):

> Scripting: Allow user code to build against .NET Standard 2.1 and .NET Framework 4.8

**Comment by dahlia** [comment]
@planetarium/nine-chronicles-engineers Do you have any plan to upgrade Unity version of Nine Chronicles?

**Comment by dahlia** [comment]
New Unity LTS which [supports .NET Standard 2.1](https://docs.unity.cn/Manual/WhatsNew2021LTS.html) is finally available now: [Unity 2021 LTS](https://docs.unity.cn/Manual/WhatsNew2021LTS.html).
