### ISSUE TITLE
CS0012 errors shown when using VSCode for development

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#1269]
When opened with VSCode, the following `CS0012` errors are shown in problems tab:

![Screenshot](https://user-images.githubusercontent.com/25877496/116195028-9ac76f00-a76c-11eb-8489-049687493093.png)

This does not seem to affect the `dotnet build` command, and the error messages can be suppressed by adding `Microsoft.Bcl.AsyncInterfaces` to the relevant project.

**Comment by longfin** [comment]
It seems resolved. (at 623f97c324850f1d14af3f8e643b0b06f722a213)
