### ISSUE TITLE
Add `planet block` command for querying

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#1285]
It would be great if we can query block information via `planet block` subcommand.

**Comment by kfangw** [comment]
I am not familiar with rockdb. So I am afraid that it may not possible for the command that reads the DB held by the active node. If then, the second option can be used only for debugging purposes.

So I would like to implement the first option first. Is it OK for you?

**Comment by kfangw** [comment]
Thanks for your kind explanation. :)
I will be working on implementing the second option first by using the `Store` interface.
