### ISSUE TITLE
Update `BlockHash.Equals()` and `HashDigest<T>.Equals()`

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#1286]
Current implementations of `Equals()` in two classes seem to have no good reason. For example in `HashDigest<T>`, we have

```
for (int i = 0; i < Size; i++)
{
    if (!ByteArray[i].Equals(other.ByteArray[i]))
    {
        return false;
    }
}

return true;
```

If the performance is of the concern, simple equality of `==` should suffice for smaller sized `byte` arrays. If the size is sufficiently large, then `SequenceEqual()` is better for both readability and efficiency. Looping over indices *and* using Linq expression do not seem to have any distinct advantage. Considering the length of arrays involved, probably `==` would be better, but I propose we change this either way.

**Comment by dahlia** [comment]
It is intended to avoid [timing attacks](https://en.wikipedia.org/wiki/Timing_attack).  In the same manner, [many cryptographic hash implementations provide their own equality test function and warn against using language's plain `==` operator (or `SequenceEqual()` method).](https://security.stackexchange.com/a/83671)

**Comment by greymistcube** [comment]
I understand, and I'm assuming base reference type has `==` comparing addresses by default. I would, indeed prefer using `Equals()` to overloading `==` in general from an OOP perspective. I guess it might come down to personal preferences. For built-in "primitives", for me at least, `==` seemed more natural. 🙃
