### ISSUE TITLE
Typo in `Libplanet.Explorer.Queries.Query.IsValidTransacion`

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#1290]
There is [a typo `IsValidTransacion`](https://github.com/planetarium/libplanet/blob/e407618beb9157a1afa7649185e7e6d1ae75d9fb/Libplanet.Explorer/Queries/Query.cs#L203) but it should be `IsValidTransaction`.

**Comment by himanshu007-creator** [comment]
i would like to work on this issue

**Comment by moreal** [comment]
Okay, @himanshu007-creator. I assigned you to this issue, you can start to work! Thanks 🙏🏻

**Comment by moreal** [comment]
Okay, @himanshu007-creator. I assigned you to this issue, you can start to work! Thanks 🙏🏻
