### ISSUE TITLE
Streamline `Block<T>` evaluation process

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#1301]
It seems current `Block<T>` evaluation is unnecessarily complicated resulting in high dependency. When evaluating `IAction`s of a `Block<T>`, necessary information pertaining to evaluation is passed on to several different classes:

* `BlockEvaluator`: `Block<T>` instance
* `Block<T>`: `AccountStateGetter`, `AccountBalanceGetter`
* `Transaction<T>`: meta info of `Block<T>`
* `ActionEvaluation`: meta info of `Block<T>` and `Transaction<T>`

As evaluation from `Block<T>` and `Transaction<T>` classes rely on external context, I don't think these classes should have their own instantiated evaluation methods. I propose moving `Block<T>.Evaluate()` and `Transaction<T>.EvaluateActions()` to either `BlockEvaluator` or some other external helper class.

**Comment by dahlia** [comment]
Historically speaking, `BlockEvaluator` was introduced along with MPT much later than others, and it purposed to eliminate circular dependency that `BlockChain<T>()` requires a `genesisBlock` and the genesis block needs to know how to evaluate its block action (for its state root hash) hash at a time.  At that time, it was (probably) considered as a workaround of that, so we've never tried to give `BlockEvaluator` the dedicated role in evaluating actions.  If we're willing to give such role to `BlockEvaluator`, IMHO we'd better rename it, like `ActionEvaluator` for example.

**Comment by greymistcube** [comment]
Yes, I agree renaming `BlockEvaluator` to something else might be better, as a newly created class might have to additionally expose something like "`EvaluateTransaction()`". If there is no larger issue in regards to separating evaluation from `Block<T>` and `Transaction<T>` entities, I'll be temporarily working on this first before continuing with #1164.

**Comment by dahlia** [comment]
> If there is no larger issue in regards to separating evaluation from `Block<T>` and `Transaction<T>` entities, I'll be temporarily working on this first before continuing with #1164.

If we separate two things it is probably for better testability.

**Comment by dahlia** [comment]
> Historically speaking, `BlockEvaluator` was introduced along with MPT much later than others, and it purposed to eliminate circular dependency that `BlockChain<T>()` requires a `genesisBlock` and the genesis block needs to know how to evaluate its block action (for its state root hash) hash at a time. At that time, it was (probably) considered as a workaround of that, so we've never tried to give `BlockEvaluator` the dedicated role in evaluating actions.

Further reading: 5afd21b4c360b887c68764543cb5271ed32ca39d.
