### ISSUE TITLE
Fix typo `Block<T>.CalcualteTxHashes()` to `Block<T>.CalculateTxHashes()`

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#1303]
The title says it all.

**Comment by himanshu007-creator** [comment]
HI i would like to work on this issue

**Comment by greymistcube** [comment]
Welcome to the project!

It's in `Libplanet/Blocks/Block.cs`.

https://github.com/planetarium/libplanet/blob/d64e92c4a29df7f866dc4ef72f89916a60f73711/Libplanet/Blocks/Block.cs#L697
