### ISSUE TITLE
`0.11.1` version hadn't released to NuGet successfully

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#1335]
Currently, there has been `0.11.1` tag since #1260 but `0.11.1` hadn't released succefully. It was because [the `VersionPrefix` in `Libplanet/Libplanet.csproj` at `0.11.1`](https://web.archive.org/web/20210605120053/https://github.com/planetarium/libplanet/blob/44ba0834a243b3616f5fbb2056f48b2ec65436e8/Libplanet/Libplanet.csproj) is not updated to `0.11.1`.

It should be re-released again.

**Comment by dahlia** [comment]
Was this already resolved by PR #1337?

**Comment by moreal** [comment]
IMO not yet. We should tag `0.11.1` to current [0.11-maintenance HEAD](https://github.com/planetarium/libplanet/commit/f19f91d67de6841d326e15fcced6facd02a2e7f7) again.

**Comment by moreal** [comment]
It seems resolved https://www.nuget.org/packages/Libplanet/0.11.1 🎉
