### ISSUE TITLE
Broadcast received block before evaluation

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#1344]

**Comment by longfin** [comment]
On second thought, this can be a little tricky. The current block synchronization process follows these steps:

1. Node A with a new block added broadcasts its block header throughout its peer list.
2. After receiving the block header from node A, node B summarizes its chain and asks node A where to get it.
3. A receives a query from node B, and delivers a list of block headers that node A should receive.
4. Node B queries and receives the block list sent by node A, and completes its chain.

The problem is that if node B receives only the block header in step 1 and forwards it to other Node C, Node C cannot complete steps 2 to 4 due to node B doesn't have a chain digest for the new block...

**Comment by dahlia** [comment]
How about embedding its own locator to block headers? (Note that for each block its block locator is deterministic.) This enables receivers to immediately determine what blocks need to be filled first.

As it would be like a richer version of `Block<T>.PreviousHash` and `Block<T>.GenesisHash`, I suggest the name `PreviousHashes` if we add the new field.
