### ISSUE TITLE
`Block<T>.Mine()` - `BlockChain<T>.Append()` doesn't work

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#1345]
```csharp
                    // assume _chain is BlockChain<PolymorphicAction<ActionBase>>
                    Transaction<PolymorphicAction<ActionBase>> authProof = StageProofTransaction();
                    Block<PolymorphicAction<ActionBase>> tip = _chain.Tip;
                    Block<PolymorphicAction<ActionBase>> block = Block<PolymorphicAction<ActionBase>>.Mine(
                        tip.Index + 1,
                        _chain.Policy.GetNextBlockDifficulty(_chain),
                        tip.TotalDifficulty,
                        Address,
                        tip.Hash,
                        DateTimeOffset.UtcNow,
                        new[] { authProof },
                        Block<PolymorphicAction<ActionBase>>.CurrentProtocolVersion,
                        cancellationToken
                    );
                    _chain.Append(block);
```

The above code throws `InvalidBlockStateRootHashException` due to `block` doesn't have a state root hash yet and `.Append()` doesn't care about this case.

Currently, users can mine block only through `BlockChain<T>.MineBlock()` API.

**Comment by greymistcube** [comment]
Do we want to allow mining through `Block<T>.Mine()`? Mining is inherently dependent on the state of the chain it is trying to work on. I'd say querying all the necessary information from the chain and manually passing them to `Block<T>.Mine()` needn't be publicly exposed in the first place. But if we really want it to be the case, a *proper* implementation would require a design change. We can of course pass the previous states of the block it is evaluating from, the evaluator, and the policy action to the `Block<T>.Mine()` method, but at that point, I think would be more sensible to just use the hash function to find the nonce and create a block using a constructor. 😶
