### ISSUE TITLE
Typo in `Libplanet.Tx.Transaction<T>.Create()` method's docs

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#1376]
There is a sentence to describe when the exception will be thrown, `Thrown when null is passed to privateKey or or actions.`.
To me, the continuous two `or`s look like a typo. https://github.com/planetarium/libplanet/blob/d3ea9492145db52d4b0295b2d87b333b2b2c51a2/Libplanet/Tx/Transaction.cs#L398-L399

![image](https://user-images.githubusercontent.com/26626194/124716592-3b8d9400-df3f-11eb-9bef-d81ebeef4f9d.png)

P.S. If it is correct grammer which I don't know, you can close this issue anytime.

**Comment by dineshkumar12004** [comment]
Can i work on this issue @moreal

**Comment by moreal** [comment]
> Can i work on this issue @moreal 
> 
> 

Hello, @dineshkumar12004. Yes, you can work on this issue 😉 I assigned you on this issue.

**Comment by dineshkumar12004** [comment]
hey since this is a simple typo fix should i need to run test or simple pr submission will work ?
