### ISSUE TITLE
Stuck at 6/10 (100%) or 7/10 (any%) during preload

### ISSUE THREAD

**Issue by PoohVz** [planetarium/libplanet#1490]
https://cdn.discordapp.com/attachments/653951482395361301/886199194312917002/logs.zip

https://cdn.discordapp.com/attachments/653951482395361301/886511950484340748/logs.rar
https://cdn.discordapp.com/attachments/653951482395361301/886521644510769153/main.old.zip

https://cdn.discordapp.com/attachments/653951482395361301/886535740966711306/main.rar

https://cdn.discordapp.com/attachments/653951482395361301/886572893125902376/log_files.zip

Will update more logs

**Comment by PoohVz** [comment]
uoocheeng#6237
https://cdn.discordapp.com/attachments/653951482395361301/887011280702021702/logs.rar

**Comment by PoohVz** [comment]
Iop#6815
https://cdn.discordapp.com/attachments/653951482395361301/887016776074928208/logs.zip

**Comment by xxsavexx** [comment]
[logs.zip](https://github.com/planetarium/libplanet/files/7156131/logs.zip)

**Comment by jannrevv** [comment]
[logs.zip](https://github.com/planetarium/libplanet/files/7156235/logs.zip)

stuck at 60% as well. attached logs.

**Comment by Erzh97** [comment]
stuck at 6/10 as well. 
[Logs.zip](https://github.com/planetarium/libplanet/files/7157172/Logs.zip)

**Comment by yuri232** [comment]
stuck at 6/10 as well
[logs.zip](https://github.com/planetarium/libplanet/files/7161203/logs.zip)

**Comment by longfin** [comment]
@PoohVz Have you received other reports after Sep? (if not, I'll close this issue)

**Comment by PoohVz** [comment]
oh, there is no new report since then, I will close it
