### ISSUE TITLE
Deprecate `MonoRocksDBStore`

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1513]
`MonoRocksDBStore` is not well maintained since `RocksDBStore` is deployed as the default option in Nine Chronicles.  It's expensive to maintain this legacy implementation while we continuously improve `RocksDBStore`.

As the option for `MonoRocksDBStore` is still available in the Nine Chronicles, and quite many players of it seem to use the option, we should announce its deprecation to the community first.

**Comment by area363** [comment]
@dahlia I've just created a PR in the snapshot-manager(https://github.com/FioX0/9c-snapshot-manager/pull/5) which is currently being used in the community. I'll make the announcement as well once this PR is merged 🙏

**Comment by dahlia** [comment]
> @area363 Could you announce this possibly breaking change to the community? I'm going to annotate `MonoRocksDBStore` with [`[Obsolete]` attribute](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=netstandard-2.0) first at 0.19.0, and completely get rid of it later at 0.20.0.

We forgot to mark it `[Obsolete]` in the 0.19.0 release.  I'm going to annotate `MonoRocksDBStore` with `[Obsolete]` in the next release, 0.20.0.
