### ISSUE TITLE
Mitigate flakiness of CI/CD

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1547]
The last few weeks, we haven't been able to merge pull requests with the complete green checks nor seen the green status badge from the README:

> [![Build Status](https://dev.azure.com/planetarium/libplanet/_apis/build/status/planetarium.libplanet?branchName=main)][Azure Pipelines]

<img src="https://user-images.githubusercontent.com/12431/138620367-52658e80-5f9c-4e26-8b29-142cb06eac19.png" width="25%" height="25%">

To me, it looks quite dangerous because we are getting insensitive to red lights.  At least, we should be able to see more greens than reds.

[Azure Pipelines]: https://dev.azure.com/planetarium/libplanet/_build?definitionId=3&_a=summary&repositoryFilter=3&branchFilter=622%2C622%2C622%2C622

---

Related issues and pull requests:

- [x] <https://github.com/planetarium/libplanet/issues/1521>
    - <https://github.com/planetarium/libplanet/pull/1548>
- [x] <https://github.com/planetarium/libplanet/pull/1544>
- [x] <https://github.com/planetarium/libplanet/pull/1549>
- [x] <https://github.com/planetarium/libplanet/issues/1550>
- [ ] <https://github.com/planetarium/libplanet/issues/1555>
- [x] <https://github.com/planetarium/libplanet/pull/1561>
- [x] #1584

**Comment by riemannulus** [comment]
```
[xUnit.net 00:01:09.38]     Libplanet.Tests.Blockchain.Renderers.DelayedActionRendererTest.ClearRenderBufferWhenItsInterval [FAIL]
  X Libplanet.Tests.Blockchain.Renderers.DelayedActionRendererTest.ClearRenderBufferWhenItsInterval [1m 7s]
  Error Message:
   Assert.Equal() Failure
Expected: 17
Actual:   14
```
