### ISSUE TITLE
Less stateful RawTransaction

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#172]
Context:

> [Maybe it's better to change the type of `RawTransaction.Actions`... 😕][1]

> [Currently `RawTransaction` consists of many mutable types like `byte[]` and `Dictionary<K, V>`.  If we want `RawTransaction` to be freer from state I believe we need to adjust other fields too.  Seems like it should be a separated patch.][2]

[1]: https://github.com/planetarium/libplanet/pull/169#discussion_r271580759
[2]: https://github.com/planetarium/libplanet/pull/169#discussion_r271595495

**Comment by longfin** [comment]
[In `Libplanet/Tx/RawTransaction.cs`](https://github.com/planetarium/libplanet/blob/9a3ef0d/Libplanet/Tx/RawTransaction.cs#L93-L103)

```
        public long Nonce { get; }

        public byte[] Signer { get; }

        public byte[] PublicKey { get; }

        public byte[][] UpdatedAddresses { get; }

        public string Timestamp { get; }

        public byte[] Signature { get; }

        public IEnumerable<IDictionary<string, object>> Actions { get; }
```

- `byte[]` → `ImmutableArray<byte>`
- ` IEnumerable<IDictionary<string, object>>` → `IEnumerable<IImmutableDictionary<string, object>>`

**Comment by minhoryang** [comment]
I'll handle this.
