### ISSUE TITLE
Add MinerAddress to ActionContext

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet#173]
Currently, since there is no miner information in the `ActionContext`, there is no way to know who is a miner.

**Comment by dahlia** [comment]
What name would be appropriate for this property?

- `BlockMinerAddress`
- `BlockMiner`
- `MinerAddress`
- `Miner`

**Comment by earlbread** [comment]
How about `Miner`? Because there is `Signer` already.

**Comment by dahlia** [comment]
> Because there is `Signer` already.

Since there's no property like `Block<T>.Signature` the term “signer” seems inappropriate for blocks.

**Comment by earlbread** [comment]
But `ActionContext` properies are:
```
public Address Signer { get; }
public long BlockIndex { get; }
public bool Rehearsal { get; }
public IAccountStateDelta PreviousStates { get; }
public IRandom Random { get; }
```
I thought it would be appropriate to add `public Address Miner` below `Signer`.
What do you think is appropriate?

**Comment by dahlia** [comment]
For consistency, `Miner` without any prefix/suffix seems good.
