### ISSUE TITLE
Use `NetMQTransport` in test projects

### ISSUE THREAD

**Issue by limebell** [planetarium/libplanet#1761]
Because `TcpTransport` is default option in `Swarm<T>`, but main usage of `Libplanet` is `NetMQTransort`. It should be tested as well, or at least replace all tests using `TcpTransport` to `NetMQTransport`.

**Comment by dahlia** [comment]
It would be better if `Libplanet.Tests` can switch the transport to test using an environment variable.  E.g.:

```bash
TEST_TRANSPORT=tcp dotnet test --project Libplanet.Net.Tests  # Run tests using TcpTransport
TEST_TRANSPORT=netmq dotnet test --project Libplanet.Net.Tests  # Run tests using NetMQTransport
```
