### ISSUE TITLE
Use another RocksDBSharp fork?

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1848]
Currently the *Libplanet.RocksDBStore* project depends on [RocksDBSharp] ([repo](https://github.com/warrenfalk/rocksdb-sharp)), but as its upstream has been inactive since 2019, we've had to maintain our own fork, [Planetarium.RocksDBSharp] ([repo](https://github.com/planetarium/rocksdb-sharp)).  However, our fork is also barely maintained, and it even bundles RocksDB binaries of v6.6, which is way behind.[^1]

Fortunately, there is another fork named [RocksDB] (that's a NuGet name; [repo](https://github.com/curiosity-ai/rocksdb-sharp)), which is actively maintained by @curiosity-ai.  They has twice the commits of the original repo, and their latest commit was made just several hours ago (as of 2022-03-11).  They're more promising and rather the upstream.

However, before switching over to their fork, we need to send our downstream patches to them first:

- <https://github.com/planetarium/rocksdb-sharp/pull/1>
- <https://github.com/planetarium/rocksdb-sharp/pull/4>

Also, they don't bundle native binaries for linux-arm64 and osx-arm64.  (They appear to have willing to support the latter though.  See also: <https://github.com/curiosity-ai/rocksdb-sharp/issues/15>.)

[^1]: Note that RocksDB 6.6 was released in 2019.  Its latest version as of 2022-03-11 is v6.29.

[RocksDBSharp]: https://www.nuget.org/packages/RocksDBSharp/
[Planetarium.RocksDBSharp]: https://www.nuget.org/packages/Planetarium.RocksDBSharp/
[RocksDB]: https://www.nuget.org/packages/rocksdb/
[1]: https://github.com/planetarium/rocksdb-sharp/tree/master/RocksDbSharp/runtimes

**Comment by dahlia** [comment]
On bundling native libraries for linux- and osx-arm64 to @curiosity-ai's fork:

- I write a proposal to support linux-arm64: <https://github.com/curiosity-ai/rocksdb-sharp/issues/20>.
- There's already the on-going discussion on osx-arm64: <https://github.com/curiosity-ai/rocksdb-sharp/issues/15>.

**Comment by theolivenbaum** [comment]
Hi there again! I'll check the two PRs later today and get them merged on our fork!

**Comment by Akamig** [comment]
@theolivenbaum Hi, I'm going to merge these two repositories with yours from today.

**Comment by theolivenbaum** [comment]
We've released it already for osx-arm64, but if you manage to test it for linux-arm64, would be great to find out if it works!

**Comment by riemannulus** [comment]
At #3487, We finally tried to change our `RocksDb` backend.

**Comment by riemannulus** [comment]
https://github.com/planetarium/libplanet/pull/3487 Done
