### ISSUE TITLE
Difficulty adjustments doesn't work as expected.

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#186]
Version: 0.3.0-nightly.20190408

The block creation policy(`BlockPolicy<T>`) is set as below and the difficulty isn't adjusted when it is mined.

```
var policy = new BlockPolicy<PolymorphicAction<ActionBase>>(TimeSpan.FromSeconds(10));
var blockChain = new BlockChain<PolymorphicAction<ActionBase>>(policy, new FileStore(path), chainId);

while (true) 
{
    blockChain.MineBlock(UserAddress);
}
```

**Comment by dahlia** [comment]
@longfin Do you think this is still valid?

**Comment by longfin** [comment]
> @longfin Do you think this is still valid?

Nope, I think this has been resolved.
