### ISSUE TITLE
Get rid of Equals.Fody

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1866]
Currently several types depend on [*Equals.Fody*](https://github.com/Fody/Equals) package.  It expands hidden members for equality test at compile-time.  Generated members include:

- [`object.Equals()`](https://docs.microsoft.com/en-us/dotnet/api/system.object.equals)
- [`object.GetHashCode()`](https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode)
- [`IEquatable<T>.Equals()`](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1.equals)
- [`operator ==()`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators#equality-operator-)
- [`operator !=()`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators#inequality-operator-)

It was introduced when C# did not support [records](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records) yet, but things are different now.  We may introduce only records from C# 9 without dropping .NET Standard 2.0 (see also #1266).

**Comment by limebell** [comment]
Closed by #1891
