### ISSUE TITLE
The chain follows the shortest neighbor

### ISSUE THREAD

**Issue by riemannulus** [planetarium/libplanet#1892]
Since #1699, the logic about block sync is changed like that.

```mermaid
sequenceDiagram
autonumber
  participant NW as Network
  participant MH as MessageHandler()
  participant FB as FillBlocksAsync()
  participant BCT as BlockCandidateTable
  participant CBC as ConsumeBlockCandidates()
  NW->>MH: Add BlockDemand
  loop download blocks
    FB-)MH: Request all BlockDemand
    MH->>FB: Return all BlockDemand
    par download block with parallel
      FB->>FB: Download Blocks
      FB->>BCT: Add Blocks to BlockCandidateTable
    end
  end
  loop Append blocks
    CBC-)BCT: Get blocks by current tip
    BCT->>CBC: Return blocks
    loop Append block to BlockChain<T>
      CBC->>CBC: Append block to BlockChain<T>
    end 
  end
```

And the following flowchart is about `[download block with parallel]`.

```mermaid
flowchart
    MS[Start] -- BlockDownload start by n --> P1[Parallel 1] 
    P1 --> A[Download blocks until n + 10 from node A] & B[Download blocks until n + 20 from node B]
    A -- Download blocks at 10 sec --> P2[Parallel 2]
    B -- Download blocks at 20 sec --> P2
    P2 --> C[Try to add blocks to BlockCandidatesTable]
    C --> D[Check already downloaded blocks using current tip as a key]
    D --> Q1{is it?}
    Q1 --> |Yes| Ignore
    Q1 --> |No| E[Add to BlockCandidatesTable]
    E --> F[BlockCandidatesTable]
    Ignore -- loop --> MS
    E -- loop --> MS
    subgraph Add to BlockChain
        F -- Get blocks using current BlockChain tip as a key --> SA[Add blocks to BlockChain]
        SA -- Finish Add --> SB[Remove outdated candidates]
        SB -- loop --> F
    end 
    style P1 fill:black,color:black
    style P2 fill:black,color:black
```

`BlockCandidateTable` is a key-value table and it is use a `BlockChain<T>.Tip` as a key when starting download blocks.
When n is `BlockChain<T>.Tip.Index` and n is 10, download blocks from node A from 10 to 20 and from node B from 10 to 30.
In this case, node A's chain downloaded way faster than node B's chain.

So, in this case, start to `Add to BlockChain` flow with node A's chain. and nod B's chain is deprecated on the `Remove outdated candidates` process.
Because blocks downloaded from node B are calculated locator from n, not n + 10.

In this case, you may have some questions.
1. Why are dropped all blocks is the problem?
    - Imagine if some node, we called it node A in here, sending the shortest blocks so cannot start to `Add to BlockChain` flow if the longest blocks download from node B?
    And if it is repeated? the current node cannot follow node B. It causes a sync problem.
    - The most important thing is until append blocks from node A to the current chain, download blocks from node B from current tip 'n'. So we cannot use downloaded blocks until block append is finished.
2. Why dropped all blocks? why don't use node B's left blocks?
    - If the chain is not reorged, can use node B's left blocks. (e.g from n + 10 to n + 20) But what if node A's chain occurred reorg and node B's chain is not? 
    For example, download blocks from node A from n - 10 to n + 10 and from node B from n to n + 30. In this case, at first, node A is synced with reorg.
    after then, try syncing node B but it cannot, node B does not compatible with node A's chain. Cannot find branchpoint too.
    - IMO, it may cause deep reorg because the current chain is too late to recognize the chain is fallen local optima.

**Comment by riemannulus** [comment]
In this context, I suggest `Download block from virtual tip`. this is download blocks from highest block at current appending blocks. It is a escape from question 1, second bullet.
Appending blocks is take a lot of time so we can use downloaded blocks when appending blocks. And it can compare each downloaded blocks until the append is finished.

**Comment by greymistcube** [comment]
First time going through `BlockCandidateTable`, so correct me if I am wrong:

- `BlockCandidateTable` is largely akin to `Dictionary<K, V>` where `K` is the `Tip` at the time of downloading `V` which is essentially a `List` of `Block<T>`s.
- When looking up the `BlockCandidateTable`, this ensures that `V` retrieved by `K` can be appended to the `BlockChain<T>` as long as its `Tip` is `K`.
- In other words, depending on how `Tip` has changed overtime, there is no guarantee that a `V` can be appended to `BlockChain<T>` if `K` is different from the current `Tip`. This doesn't necessarily mean trying to append `V` *will* fail. As mentioned above, such scenarios simply exist, as in the case of reorgs.

Am I understanding it right?

**Comment by riemannulus** [comment]
> In other words, depending on how `Tip` has changed overtime, there is no guarantee that a `V` can be appended to `BlockChain<T>` if `K` is different from the current `Tip`. 

Yes, it is.

>  This doesn't necessarily mean trying to append `V` will fail. As mentioned above, such scenarios simply exist, as in the case of reorgs.

If you saying case `not reorged between node A and B`, it is right. It can be trying to append `V` from node B.

**Comment by greymistcube** [comment]
Here's a mock-up `interface` for concurrent `BlockCandidateTable<T>` idea that we've talked about. 😗

https://gist.github.com/greymistcube/9c64bc93be1444000fb2cf83e37888a6

**Comment by riemannulus** [comment]
> Here's a mock-up `interface` for concurrent `BlockCandidateTable<T>` idea that we've talked about. 😗
> 
> https://gist.github.com/greymistcube/9c64bc93be1444000fb2cf83e37888a6 

Thanks for your idea! It makes me clear what we said.

**Comment by riemannulus** [comment]
The basic concept of @greymistcube is like this. If `node X` has a follow chain,
```mermaid
flowchart LR
    A --> B --> C --> D
```
cause following situation when downloaded blocks from `node A` and `node B`

```mermaid
flowchart LR
    A --> B --> C --> D
    B -- from chain A --> C' --> D'
    D -- from chain B --> E --> F --> G --> H
```
in this case, `chain A` will start to append to `BlockChain<T>` first.

```mermaid
flowchart LR
    A --> B  --> C' --> D'
    D -- from chain B --> E --> F --> G --> H
```
The concrete idea of @greymistcube is updating all downloaded branches. filling like this

```mermaid
flowchart LR
    A --> B  --> C' --> D'
    B --> C --> D -- from chain B --> E --> F --> G --> H
```

and `swap` chain to longest branch
```mermaid
flowchart LR
    A --> B --> C --> D --> E --> F --> G --> H
```

here is more example. if changed tip like this.

```mermaid
flowchart LR
    A --> B  --> C' --> D'
    D -- from chain B --> E --> F --> G --> H
    D -- from chain C --> CE[E] --> CF[F] --> CG[G] --> CH[H] --> CI[I] --> CJ[J]
```

next step is update all branches in `BlockCandidateTable<T>`
```mermaid
flowchart LR
    A --> B  --> C' --> D'
    B --> C --> D -- from chain B --> E --> F --> G --> H
    D -- from chain C --> CE[E] --> CF[F] --> CG[G] --> CH[H] --> CI[I] --> CJ[J]
```

then find longest branch in `BlockCandidateTable<T>`
```mermaid
flowchart LR
    A --> B --> C --> D --> E --> F --> G --> H --> I --> J
```

**Comment by greymistcube** [comment]
Seems about right. It might be useful to have separate `BlockCandidateTable` diagram for clarity.

After downloading from `node A`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    B_A[B] --> C_A'[C'] --> D_A'[D'] --> E_A'[E']
    end

    subgraph BlockChain
    direction LR
    A --> B --> C --> D
    end
```

While appending the best branch from `BlockCandidateTable` to `BlockChain`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    B_A[B] --> C_A'[C'] --> D_A'[D'] --> E_A'[E']
    end

    subgraph Path
    direction LR
    D_P[D] --> C_P[C] --> D_P'[D'] --> E_P'[E']
    end

    subgraph BlockChain[BlockChain - append in progress]
    direction LR
    A --> B --> C --> D
    C --> D' --> E'
    end
    style BlockChain fill:#f77

    BlockChain -.->|derived| Path
```

After downloading from `node B`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    B_A[B] --> C_A'[C'] --> D_A'[D'] --> E_A'[E']
    D_B[D] --> E_B[E] --> F_B[F]
    end

    subgraph Path
    direction LR
    D_P[D] --> C_P[C] --> D_P'[D'] --> E_P'[E']
    end

    subgraph BlockChain[BlockChain - append in progress]
    direction LR
    A --> B --> C --> D
    C --> D' --> E'
    end
    style BlockChain fill:#f77

    BlockChain -.->|derived| Path
```

After done updating `BlockChain`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    B_A[B] --> C_A'[C'] --> D_A'[D'] --> E_A'[E']
    D_B[D] --> E_B[E] --> F_B[F]
    end

    subgraph Path
    direction LR
    D_P[D] --> C_P[C] --> D_P'[D'] --> E_P'[E']
    end

    subgraph BlockChain
    direction LR
    A --> B --> C --> D' --> E'
    end
```

Trigger update `BlockCandidateTable` with `Path`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    B_A[B] --> C_A'[C'] --> D_A'[D'] --> E_A'[E']
    D_B[D] --> E_B[E] --> F_B[F]
    end

    subgraph Path
    direction LR
    D_P[D] --> C_P[C] --> D_P'[D'] --> E_P'[E']
    end

    subgraph BlockChain
    direction LR
    A --> B --> C --> D' --> E'
    end

    Path -.->|update| BlockCandidateTable
```

Updating `BlockCandidateTable` with `Path`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    B_A[B] --> C_A'[C'] --> D_A'[D'] --> E_A'[E']
    C_B[C] --> D_B[D] --> E_B[E] --> F_B[F]
    end

    subgraph Path
    direction LR
    D_P[D] --> C_P[C] --> D_P'[D'] --> E_P'[E']
    end

    subgraph BlockChain
    direction LR
    A --> B --> C --> D' --> E'
    end

    Path -.->|update| BlockCandidateTable
    style B_A fill:#777
    style C_A' fill:#777
    style D_A' fill:#777
    style E_A' fill:#777
    style C_B fill:#7f7
```

After done updating `BlockCandidateTable` with `Path`:

```mermaid
flowchart TD
    subgraph BlockCandidateTable
    direction LR
    C_B[C] --> D_B[D] --> E_B[E] --> F_B[F]
    end

    subgraph BlockChain
    direction LR
    A --> B --> C --> D' --> E'
    end
```

**Comment by greymistcube** [comment]
Oops, there were some mistakes in the above comment. Just fixed it.
