### ISSUE TITLE
Action evaluation order implicitly depends on Equals.Fody's `GetHashCode()` algorithm

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#1897]
Seemingly action evaluation order implicitly depends on Equals.Fody's `GetHashCode()` algorithm.  This kind of implicit behavior should be turned to an explicit one.  In other words, we should define our own algorithm rather than depending on third-party code, which is not guaranteed to be unchanged in the future.

**Comment by limebell** [comment]
Closed by #1891
