### ISSUE TITLE
Prepare to move to .NET 6 LTS (drop .NET Core 3.1)

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#1931]
When I looked at the [.NET Core lifecycle][net-core-lifecycle], the .NET 3.1 LTS will be deprecated on December 3, 2022.
It's not something to do in a hurry right now, but I leave it as a notice.

[net-core-lifecycle]: https://docs.microsoft.com/ko-kr/lifecycle/products/microsoft-net-and-net-core

**Comment by dahlia** [comment]
Possibly related to #1266.

**Comment by dahlia** [comment]
Actually, our library assemblies do not depend on .NET Core 3.1, but target .
NET Standard 2.0 & 2.1.  Only executables like tests and `planet` depend on .NET Core 3.1.

**Comment by longfin** [comment]
Related Issues

For test projects: #2164
For CLI (`planet`): #2161
