### ISSUE TITLE
Limit size of block (byte-wise)

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#201]
Currently, Libplanet doesn't define how many transactions will be stored in a block, and the size of a transaction is also not explicitly defined. however, in order to predict figures such as storage space and network traffic, it is necessary to be able to determine how much physical space a block occupies.

The block size is not a protocol-level constraint, and game developers need to adjust the unit to synchronize the status of each game, so I suggest offering it as an configurable parameter.

**Comment by longfin** [comment]
Block size can be defined in two ways. 

1. total bytes
2. a count of transactions.

In many other blockchain projects, they prefer to limit by byte size. it's useful to predict disk space, network traffic, and discovering attack scenarios. 
but limiting by a count of transactions can be also useful because it can affect the performance of executing blocks directly. (and it can be more straightforward for game devs)

So, it would be useful if we add parameters like as `TotalBlockSize` and `TotalTxCount` to `BlockPolicy` and restrict block using them.

**Comment by dahlia** [comment]
I'm going to work on this.
