### ISSUE TITLE
Add GraphQL Schema file for Libplanet.Explorer

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#2016]

**Comment by Akamig** [comment]
```
schema {
  query: ExplorerQuery
}

type ExplorerQuery {
  //You can query 
  blockQuery: BlockQuery
  transactionQuery: TransactionQuery
  nodeState: NodeState!
}

type BlockQuery {
  blocks(
    desc: Boolean = false
    offset: Int = 0
    limit: Int
    excludeEmptyTxs: Boolean = false
    miner: Address
  ): [Block!]!
  block(hash: ID, index: ID): Block
}

type Block {
  hash: ID!
  index: Long!
  difficulty: Long!
  totalDifficulty: BigInt!
  nonce: ByteString!
  miner: Address!
  publicKey: PublicKey
  previousBlock: Block
  timestamp: DateTimeOffset!
  stateRootHash: ByteString!
  signature: ByteString
  transactions: [Transaction!]!
}

scalar Long

scalar BigInt

scalar ByteString

scalar Address

scalar PublicKey

# The `DateTimeOffset` scalar type represents a date, time and offset from UTC. `DateTimeOffset` expects timestamps to be formatted in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
scalar DateTimeOffset

type Transaction {
  id: ID!
  nonce: Long!
  signer: Address!
  publicKey: ByteString!
  updatedAddresses: [Address!]!
  signature: ByteString!
  timestamp: DateTimeOffset!
  actions: [Action!]!
  blockRef: [Block!]
}

type Action {
  raw(encode: String = "hex"): String!
  inspection: String!
}

type TransactionQuery {
  transactions(
    signer: Address
    involvedAddress: Address
    desc: Boolean = false
    offset: Int = 0
    limit: Int
  ): [Transaction!]!
  stagedTransactions(
    signer: Address
    involvedAddress: Address
    desc: Boolean = false
    offset: Int = 0
    limit: Int
  ): [Transaction!]!
  transaction(id: ID): Transaction
}

type NodeState {
  preloaded: Boolean!
}
```

I can download this schema from playground though, I'm not sure where should we put it as a file in this Libplanet.Explorer proj.
I think we may need some kind of automation between GraphQL Playground execution and schema file parsing in order to avoid the desync of actual schema implementation and this schema file.

**Comment by longfin** [comment]
@Akamig At first, sorry for lacking content for this issue and thanks for effort.

When I posted this issue, assumed that, it would be useful when we provide `Schema` object (e.g., [StandaloneSchema](https://github.com/planetarium/NineChronicles.Headless/blob/d8db549c5eb64bf9ebd7d983f470dd98de99c766/NineChronicles.Headless/GraphTypes/StandaloneSchema.cs) in 9c) instead of `Query`s (e.g., [BlockQuery](https://github.com/planetarium/libplanet/blob/817782f3ebbca036be28888d535d18bac6562810/Libplanet.Explorer/Queries/BlockQuery.cs)) because we can simplify installation steps as bellow...

```csharp
    builder.Services
        .AddGraphQL(builder =>
        {
            builder
                .AddSchema<LibplanetExplorerSchema>()
                .AddGraphTypes(typeof(LibplanetExplorerSchema).Assembly)
                .AddSystemTextJson();
        })
        .AddCors()
        .AddSingleton<LibplanetExplorerSchema>()
        .AddSingleton<GraphQLHttpMiddleware<LibplanetExplorerSchema>>()

    using WebApplication app = builder.Build();    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGraphQLPlayground();
    });
    app.UseGraphQL<LibplanetExplorerSchema>();

    app.Run();
```

Note: In current Libplanet(0.38.0), we should define `Query` and `Schema` on app side like [1](https://github.com/planetarium/planet-node/blob/a74e17dc1c7637ef1eaa6db3f4d745f49645d47c/PlanetNode/GraphTypes/PlanetNodeQuery.cs#L13), [2](https://github.com/planetarium/planet-node/blob/a74e17dc1c7637ef1eaa6db3f4d745f49645d47c/PlanetNode/GraphTypes/PlanetNodeSchema.cs)

Thus, this issue was about `Schema` object, not schema file. 😅

**Comment by longfin** [comment]
On second thought, it seems that adding a schema file would be more appropriate as @Akamig did now. so I'll post a new issue to address [it](https://github.com/planetarium/libplanet/issues/2016#issuecomment-1151096535). 

@Akamig it's okay to keep current work on this issue, thanks!

**Comment by longfin** [comment]
#2063 seems to address this issue. thanks for effort! @Akamig
