### ISSUE TITLE
Ask storing path for keystore

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#2017]
[`key create` command](https://github.com/planetarium/libplanet/blob/2086fb9250884b4b12ff7a2af740166d78a175df/Libplanet.Extensions.Cocona/Commands/KeyCommand.cs#L32) assumes that storing keystore file to default path. it may would be better if we provide the chance to change it while creating. (like ssh-keygen)

**Comment by longfin** [comment]
But on the other hand, it may harms consistency about sub-commands in `key`... 🤔

**Comment by Akamig** [comment]
I think we can provide path changing and not harm consistency by introducing the `--path` option generally, but not mandatorily. (it's currently only used when exporting Web3 Secret Storage JSON). 
also introducing console message such as 
```
Key Created. 
Adding to default path.

Key Created.
Exporting to provided path (or print provided path here)
(and fallback to default path if fails)
```
could help users without breaking change.

On the other hand, for the long term, I think Create command should be merged with Generate command. Is there a specific reason these two commands are separated?
