### ISSUE TITLE
Provide `Schema` object instead of `Query`s

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#2065]
(cont. from https://github.com/planetarium/libplanet/issues/2016#issuecomment-1151096535)

It would be useful when we provide `Schema` object (e.g., [StandaloneSchema](https://github.com/planetarium/NineChronicles.Headless/blob/d8db549c5eb64bf9ebd7d983f470dd98de99c766/NineChronicles.Headless/GraphTypes/StandaloneSchema.cs) in 9c) instead of `Query`s (e.g., [BlockQuery](https://github.com/planetarium/libplanet/blob/817782f3ebbca036be28888d535d18bac6562810/Libplanet.Explorer/Queries/BlockQuery.cs)) because we can simplify installation steps as bellow...

```csharp
    builder.Services
        .AddGraphQL(builder =>
        {
            builder
                .AddSchema<LibplanetExplorerSchema>()
                .AddGraphTypes(typeof(LibplanetExplorerSchema).Assembly)
                .AddSystemTextJson();
        })
        .AddCors()
        .AddSingleton<LibplanetExplorerSchema>()
        .AddSingleton<GraphQLHttpMiddleware<LibplanetExplorerSchema>>()

    using WebApplication app = builder.Build();
    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGraphQLPlayground();
    });
    app.UseGraphQL<LibplanetExplorerSchema>();

    app.Run();
```

Note: In current Libplanet(0.38.0), we should define `Query` and `Schema` on the app side like ([1](https://github.com/planetarium/planet-node/blob/a74e17dc1c7637ef1eaa6db3f4d745f49645d47c/PlanetNode/GraphTypes/PlanetNodeQuery.cs#L13), [2](https://github.com/planetarium/planet-node/blob/a74e17dc1c7637ef1eaa6db3f4d745f49645d47c/PlanetNode/GraphTypes/PlanetNodeSchema.cs))

Thus, this issue was about `Schema` object, not schema file. 😅

**Comment by longfin** [comment]
@moreal Do you have any idea for it? 🙏

**Comment by kasumielf** [comment]
I want take this issue.

**Comment by longfin** [comment]
# Motivation

The main motivation of this issue is, separating between Libplanet-providing part(e.g., `Libplanet.Explorer`) and application-providing(e.g., [`PlanetNodeSchema`](https://github.com/planetarium/planet-node/blob/main/PlanetNode/GraphTypes/PlanetNodeSchema.cs)) part. 

Libplanet.Explorer provides [Queries](https://github.com/planetarium/libplanet/tree/0.40.0/Libplanet.Explorer/Queries) and [Mutions](https://github.com/planetarium/libplanet/tree/0.40.0/Libplanet.Explorer/Mutations). but it doesn't provide them as modularized schema, so users need to integrate them into thier application specific query and mutations as like as metioned.

> Note: In current Libplanet(0.38.0), we should define Query and Schema on the app side like ([1](https://github.com/planetarium/planet-node/blob/a74e17dc1c7637ef1eaa6db3f4d745f49645d47c/PlanetNode/GraphTypes/PlanetNodeQuery.cs#L13), [2](https://github.com/planetarium/planet-node/blob/a74e17dc1c7637ef1eaa6db3f4d745f49645d47c/PlanetNode/GraphTypes/PlanetNodeSchema.cs))

# Strategy

- We need to create `LibplanetExplorerSchema` like as `[PlanetNodeSchema](https://github.com/planetarium/planet-node/blob/5c607b4e91eb14f12c8fdd085ac1f20807e3b819/PlanetNode/GraphTypes/PlanetNodeSchema.cs)` on `Libplanet.Explorer` side.
- For checking about that, we may need to introduce `LibplanetExplorerSchema` to the application project (i.e., planet-node)
  - AFIK, `.UseGraphQL()` takes optional parameters for url path (e.g., `/graphql`) to distinguish endpoints for mutliple schemes.

@kasumielf

**Comment by kasumielf** [comment]
I guess ExplorerQuery already work and contains BlockQuery and TransactionQuery.([ExplorerQuery](https://github.com/planetarium/libplanet/blob/0.40.0/Libplanet.Explorer/Queries/ExplorerQuery.cs)).

In this #2198 PR, ExplorerSchema was implemented for ExplorerQuery.

Anyway, I think 'LibplanetExplorerSchema' name is better than 'ExplorerSchema'.  I'll rename it.

**Comment by moreal** [comment]
This issue seems resolved by https://github.com/planetarium/libplanet/pull/2198.
