### ISSUE TITLE
BlockChain raises KeyNotFoundException when index is not in it

### ISSUE THREAD

**Issue by ipdae** [planetarium/libplanet#208]
If there is no value at index when `BlockChain[index]` is called, [ArgumentOutofRangeException](https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception) should occur. 
But it raises ` KeyNotFoundException`, because `Store.IndexBlockHash` returns `default(T)` instead of `null`.

![image (4)](https://user-images.githubusercontent.com/3193043/56266294-cef00a00-6126-11e9-96be-192f6881b63d.png)

**Comment by longfin** [comment]
it was resolved by #317
