### ISSUE TITLE
Remove `validators` parameter from `Swarm<T>`

### ISSUE THREAD

**Issue by colibrishin** [planetarium/libplanet#2093]
`validators` parameter was added for taking `PublicKey` of `validator`. After PR https://github.com/planetarium/libplanet/pull/2086, We now takes Peers by `ConsensusPeers` and PublicKey can be retrieved from `ConsensusPeers`. We can take less parameter in `Swarm<T>` by removing redundant `validators` and create a list of validator's PublicKey from `ConsensusPeers`.

Related document is https://docs.libplanet.io/0.10.3/api/Libplanet.Net.BoundPeer.html

**Comment by OnedgeLee** [comment]
@colibrishin
So, as I understood, this issue covers not only removing [`validators` parameter from `Swarm<T>`](https://github.com/planetarium/libplanet/blob/43aaf79d6b9ece86cd4d172685cad8267c79afd7/Libplanet.Net/Swarm.cs#L89), but also
removing [argument](https://github.com/planetarium/libplanet/blob/43aaf79d6b9ece86cd4d172685cad8267c79afd7/Libplanet.Net/Consensus/ConsensusReactor.cs#L33) `_validators` of `ConsensusReactor` constructor and its [validation process](https://github.com/planetarium/libplanet/blob/43aaf79d6b9ece86cd4d172685cad8267c79afd7/Libplanet.Net/Consensus/ConsensusReactor.cs#L44-L51), right?

**Comment by colibrishin** [comment]
Yes! Note that `ConsensusContext` and `Context` do not need `BoundPeer`.
