### ISSUE TITLE
Raise exception when zero byte array applied as a argument on `PrivateKey` generation

### ISSUE THREAD

**Issue by OnedgeLee** [planetarium/libplanet#2095]
When zero byte array has been applied as a argument `byte[] unverifiedKey` on `Libplanet.Crypto.PrivateKey` [key generation](https://github.com/planetarium/libplanet/blob/6b2ccce2dc4dd7578d0bc3a9c8cdfb8081cf1479/Libplanet/Crypto/PrivateKey.cs#L381-L387), unhandled exception raised from `ECDomainParameters.ValidatePrivateScalar` in `Org.BouncyCastle.Crypto.Parameters` appears.
```
System.ArgumentException : Scalar is not in the interval [1, n - 1] (Parameter 'd')
```
It's not a bug and proper functionality, since zero multiplication on elliptic curve point is ambiguous, but this exception would be better to raised on `Libplanet` to make sure our intension.

**Comment by Gyeonghun-Park** [comment]
✋

**Comment by moreal** [comment]
It's been two years, so I'll unassign it so others can work on it.
