### ISSUE TITLE
`CHANGES.md` style

### ISSUE THREAD

**Issue by tkiapril** [planetarium/libplanet#2160]
https://github.com/planetarium/libplanet/blob/165596a764973f76c406e3b930fe323e4cf59515/CHANGES.md?plain=1#L19-L24

Styling in these lines of `CHANGES.md` are incorrect, they should be fixed to match the usual style.

**Comment by CodingPythonMan** [comment]
✋

**Comment by greymistcube** [comment]
Sorry, but this has been resolved by #2210 while tidying things up in preparation for 0.40.0 release. 😶
