### ISSUE TITLE
Bump `TargetFramework` of Libplanet.Test and other test projects

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#2164]
Currently, all test proejcts are targetting `.netcoreapp3.1`. but NET Core 3.1 will be dropped as supporting at the [end of 2022](https://dotnet.microsoft.com/en-us/platform/support/policy), and above all, .NET Core SDK 3.1 doesn't have Aarch support, so it's not available for Apple Silicon users.

Therefore, it is suggested to upgrade all the versions of the projects to .NET 6.

**Comment by tkiapril** [comment]
Related: #2161, #2090, #1931
