### ISSUE TITLE
Apparently `cref`s to other than Libplanet.dll are not resolved

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#2182]
When you see the part of the document, you can see the exceptions' link like `InvalidOperationException` or `KeyNotFoundException`.

### Examples

1. `IAccountStateDelta` ([docs](https://docs.libplanet.io/0.39.0/api/Libplanet.Action.IAccountStateDelta.html), [code](https://github.com/planetarium/libplanet/blob/739f5f36f2ba9f4fa47424809d4c26ecb06104f8/Libplanet/Action/IAccountStateDelta.cs#L10-L38))
1. `IStore.PruneOutdatedChains` ([docs](https://docs.libplanet.io/0.39.0/api/Libplanet.Store.IStore.html#Libplanet_Store_IStore_PruneOutdatedChains_System_Boolean_), [code](https://github.com/planetarium/libplanet/blob/739f5f36f2ba9f4fa47424809d4c26ecb06104f8/Libplanet/Store/IStore.cs#L336-L351))

**Comment by longfin** [comment]
@moreal Could you give more detailed info or the screen capture about the symptom you said? (I couldn't get the point 😅 )

**Comment by tkiapril** [comment]
I think it's that on the XML there is a reference to exceptions:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/7963440/181763664-30ec865f-072f-460d-a555-fb3af37461bb.png">
but once it's compiled it vanishes:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/7963440/181763734-7f9c6ae3-359e-48e4-ab01-69fa791a6f10.png">
(notice the lack of KeyNotFoundException)

**Comment by moreal** [comment]
That's what I mean, if the title made you confused, it should be corrected

**Comment by OnedgeLee** [comment]
Since our document does not have referenced exception type, it cannot be seen on document.
It would be better to use <c> tag, or link MS official document.

**Comment by tkiapril** [comment]
This may have occurred due to a MSBuild bug, refer https://github.com/dotnet/docfx/issues/8097 and https://github.com/dotnet/msbuild/issues/7832. Not sure if it's suitable as a good first issue. 🤔
