### ISSUE TITLE
`BoundPeer.PeerString` property

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#2187]
Currently `BoundPeer` provide `ParsePeer()` method, but there is no official way to get a `BoundPeer`'s peer string which can be parsed by `ParsePeer()`.  It would be good to have a property like `PeerString`.

Note that the established format is like below:

<https://github.com/planetarium/libplanet/blob/e19221ab6e59f07684c58b1f68f6ea8247a61f48/Libplanet.Net/BoundPeer.cs#L71>

**Comment by xet-a** [comment]
🙌
