### ISSUE TITLE
`planet` Could not find keystore path on circleCI

### ISSUE THREAD

**Issue by sky1045** [planetarium/libplanet#2192]
https://app.circleci.com/pipelines/github/planetarium/9c-launcher/1776/workflows/7e38a3b9-943e-41c5-b6ec-6c404e7fc322/jobs/7141/parallel-runs/0/steps/0-115

as circleCI builds 9c-launcher on container, the `planet` command cannot find keystore path correctly.

the job above executes following script.
https://github.com/planetarium/9c-launcher/blob/development/scripts/make-apv.sh

- version: planet `0.9.5`

**Comment by dahlia** [comment]
The default keystore path depends on few common environment variables.  See also:

<https://github.com/planetarium/libplanet/blob/6a360554ec3e6db21be041afbf1eaf92e0f25e3b/Libplanet/KeyStore/Web3KeyStore.cs#L21-L29>

CircleCI might be lacking some common environment variables.  Could you show me what `env` prints inside a CircleCI SSH session?

**Comment by sky1045** [comment]
```
root@3a96c90752f5:~# env
CIRCLE_WORKFLOW_JOB_ID=c2268a5a-c233-4e59-a130-b12abfab75f3
TRANSIFEX_TOKEN=<secret>
CIRCLE_PULL_REQUESTS=https://github.com/planetarium/9c-launcher/pull/1711
SENTRY_ORG=planetariumhq
HOSTNAME=3a96c90752f5
AWS_ACCESS_KEY=<secret>
AWS_SECRET_KEY=<secret>
SSH_AUTH_SOCK=/tmp/circleci-2449213834/ssh_auth_sock
CIRCLE_REPOSITORY_URL=git@github.com:planetarium/9c-launcher.git
CIRCLE_WORKING_DIRECTORY=~/project
CIRCLE_INTERNAL_CONFIG=/.circleci-runner-config.json
CIRCLECI=true
CIRCLE_PROJECT_REPONAME=9c-launcher
YARN_VERSION=1.22.19
PWD=/root
DOCKER_PASSWORD=<secret>
CIRCLE_WORKFLOW_ID=12d9b035-6c56-4b6b-b525-801020b3b033
DOCKER_USERNAME=planetariumbot
CIRCLE_PULL_REQUEST=https://github.com/planetarium/9c-launcher/pull/1711
CIRCLE_USERNAME=sky1045
CIRCLE_BRANCH=chore/circleci-cross-build
HOME=/root
GITHUB_TOKEN=<secret>
CIRCLE_PROJECT_USERNAME=planetarium
CIRCLE_BUILD_NUM=7227
CIRCLE_NODE_TOTAL=1
CHROMATIC_PROJECT_TOKEN=<secret>
CIRCLE_SHA1=<secret>
TERM=xterm-256color
NO_PROXY=127.0.0.1,localhost,circleci-internal-outer-build-agent
APV_SIGN_KEY=<secret>
CI_PULL_REQUEST=https://github.com/planetarium/9c-launcher/pull/1711
SHLVL=1
CIRCLE_BUILD_URL=https://circleci.com/gh/planetarium/9c-launcher/7227
BASH_ENV=/tmp/.bash_env-62e9faa94829ff1f63879776-0-build
SENTRY_PROJECT=9c-launcher
CIRCLE_NODE_INDEX=0
CIRCLE_WORKFLOW_WORKSPACE_ID=14bd94b2-1628-4c96-b007-3e050b9bba7f
SENTRY_AUTH_TOKEN=<secret>
CIRCLE_JOB=build-windows
CIRCLE_SHELL_ENV=/tmp/.bash_env-62e9faa94829ff1f63879776-0-build
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
CIRCLE_INTERNAL_SCRATCH=/tmp/circleci-2449213834
CI=true
CIRCLE_INTERNAL_TASK_DATA=/tmp/.circleci-task-data-62e9faa94829ff1f63879776-0-build
NODE_VERSION=16.16.0
TRANSIFEX_SECRET=<secret>
_=/usr/bin/env
```

**Comment by sky1045** [comment]
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/root/project/planetarium/keystore/planetarium/keystore/UTC--2022-08-03T05-28-08Z--(id)'.
   at Cocona.Command.Dispatcher.Middlewares.CoconaCommandInvokeMiddleware.DispatchAsync(CommandDispatchContext ctx)
   at Cocona.Command.Dispatcher.Middlewares.HandleParameterBindExceptionMiddleware.DispatchAsync(CommandDispatchContext ctx)
   at Cocona.Command.Dispatcher.Middlewares.HandleExceptionAndExitMiddleware.DispatchAsync(CommandDispatchContext ctx)
   at Cocona.Command.Dispatcher.CoconaCommandDispatcher.DispatchAsync(CancellationToken cancellationToken)
   at Cocona.Lite.Hosting.CoconaLiteAppHost.RunAsyncCore(CancellationToken cancellationToken)
```
I found the keystore file in the path `/root/project/planetarium/keystore/planetarium/keystore/` inside a SSH session.
and understand how it could be created in that path
<https://github.com/planetarium/libplanet/blob/b8b5b25ec5724b8e780fa1c052f295a3a4082926/Libplanet/KeyStore/Web3KeyStore.cs#L47-L65>

so it seems to create keystore correctly but couldn't reference it after creating.
also, if i create `.config` in $HOME directory, it works fine.

**Comment by dahlia** [comment]
It's quite strange.  The path from the error message refers to a file rather than a directory, and the filename consists of a certain timestamp and a UUID:

    /root/project/planetarium/keystore/planetarium/keystore/UTC--2022-08-02T02-57-50Z--cc78a59f-35fc-4e26-82a6-f21b3a360509

It means the program succeeded to list files in the keystore directory.  I guess the logic to join a keystore path and a key filename apparently has some bug, and it makes an incorrect file path.  As a result, the key file path starts with neither `$XDG_DATA_HOME` nor `$HOME/.config`.

**Comment by dahlia** [comment]
[`Path.Combine()`'s quick][1] might be relevant to this bug.

[1]: https://agirlamonggeeks.com/2020/10/04/c-be-careful-with-path-combine/

**Comment by sky1045** [comment]
I ran the following script inside SSH session
```
string DefaultPath = System.IO.Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
    "planetarium",
    "keystore"
);
Console.WriteLine(DefaultPath);
Console.WriteLine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
```

and the output is...
```
Hello, World!
planetarium/keystore

```

I thought that `Environment.SpecialFolder.ApplicationData` will be resolved to `/home/root/.config` but it seems to be nothing.
the container is node:16.16.0-slim which is based on Debian buster.

**Comment by dahlia** [comment]
> I thought that `Environment.SpecialFolder.ApplicationData` will be resolved to `/home/root/.config` but it seems to be nothing.

Probably relevant: <https://github.com/dotnet/runtime/issues/27582>.

**Comment by sky1045** [comment]
https://github.com/dotnet/runtime/blob/b5705587347d29d79cec830dc22b389e1ad9a9e0/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L25-L39

if the path not exist without create option, it returns empty.
need to create `$HOME/.config` in advance anyway 🤣
