### ISSUE TITLE
Let's widen the line length limit!

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#222]
Although we've adopted 80 columns for the line limit, but [it was like a procrastination rather than a proper decision][1]. It's because we didn't arrived at a consensus on the maximum number of columns to allow, but only on that we need to limit columns per line anyway.

However, we become more and more aware that 80 columns are too short to ordinary C# code.  C# is neither C nor Python, and have way longer names, and it already starts with second-level depth due to namespaces.

So I suggest to widen the line limit.

What number would be suitable for this project?  I suggest 132 characters as [Linus Torvalds did in a decade ago][2]:

> I'd be ok with changing the warning to 132 characters, which is another perfectly fine historical limit.

Except that for me the historical reason is not primary; to me the 132 characters limit looks good because it is not that wider than other candidates, e.g., 160 or 180.  If we adopt a wide line limit once, it will hardly become narrow again.  So we'd better have a small step.

[1]: https://github.com/planetarium/libplanet/pull/58#issuecomment-461724764
[2]: https://lkml.org/lkml/2012/2/3/394

**Comment by earlbread** [comment]
How about 120 characters? It is the maximum line length without horizontal scrolling of the Rider when splitting the screen into two at 1920x1080 resolution.

**Comment by dahlia** [comment]
> How about 120 characters? It is the maximum line length without horizontal scrolling of the Rider when splitting the screen into two at 1920x1080 resolution.

Doesn't it depend on font size? Anyway, 132 characters seem indeed too many for narrow displays.  In fact, 120 characters also are not fit in two columns on my main monitor…

**Comment by dahlia** [comment]
100 columns seem fit in two columns on my main monitor.

**Comment by longfin** [comment]
💯 columns seems to good.
