### ISSUE TITLE
Typo in `Libplanet.Blockchain.Policies.VolatileStagePolicy`

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#2369]
The method `Exipred` should be `Expired`.

https://github.com/planetarium/libplanet/blob/c2537a8f38a91ed57f6a012a12ce65bd381c4cda/Libplanet/Blockchain/Policies/VolatileStagePolicy.cs#L276

**Comment by greymistcube** [comment]
Closed by #2371
