### ISSUE TITLE
Introduce class `Validator` on `Libplanet.Consensus`

### ISSUE THREAD

**Issue by OnedgeLee** [planetarium/libplanet#2429]
Validators are reperesented as its `PublicKey` for now.
But on PoS consensus, also their voting power is required.
There are two options for handling them.
1. Represents validators as its public key, and maintain voting power table
2. Introduce new `Validator` class that has public key and voting power

Second one seems to be better solution.

**Comment by riemannulus** [comment]
Maybe solved in here. https://github.com/planetarium/libplanet/commit/195248ee2005474f747838ea6cdaf709c309df6b
