### ISSUE TITLE
Change docs to use `<see langword>` tags instead of `<c>` tags when applicable.

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#2435]
Currently in the codebase, both `<see langword>` and `<c>` tags are used in a mixed manner for [C# keywords]. As `<see langword>` is more appropriate for tagging [C# keywords], for consistency, I suggest changing `<c>` tags to `<see langword>` tags. Often found examples include

```xml
<c>null</c>
<c>true</c>
<c>false</c>
```

and these should be changed to

```xml
<see langword="null"/>
<see langword="true"/>
<see langword="false"/>
```

[C# keywords]: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/

**Comment by Pragya2056** [comment]
Please assign this to me

**Comment by Pragya2056** [comment]
Sorry!! But I have to back down from this due to personal problem. 
I apologize for the mis-guidance. 
Thank you!!!

**Comment by greymistcube** [comment]
@Pragya2056
No problem at all. 😀
