### ISSUE TITLE
Optimize `ByteUtil.CalculateHash()`

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#2437]
Here's a sample code for the benchmark results below:

```csharp
[Benchmark]
public int BytesUsingUnchecked()
{
    int code = 0;
    unchecked
    {
        foreach (byte b in _bytes)
        {
            code = (code * 397) ^ b.GetHashCode();
        }
    }

    return code;
}

[Benchmark]
public int ImmutableBytesUsingUnchecked()
{
    int code = 0;
    unchecked
    {
        foreach (byte b in _immutableBytes)
        {
            code = (code * 397) ^ b.GetHashCode();
        }
    }

    return code;
}

[Benchmark]
public int BytesUsingUncheckedLinq()
{
    return _bytes.Aggregate(0, (current, b) => unchecked(current * 397) ^ b);
}

[Benchmark]
public int ImmutableArrayUsingUncheckedLinq()
{
    return _immutableBytes.Aggregate(0, (current, b) => unchecked(current * 397) ^ b);
}
```

|                           Method |      Mean |    Error |    StdDev |
|--------------------------------- |----------:|---------:|----------:|
|              BytesUsingUnchecked |  94.60 us | 1.871 us |  2.743 us |
|     ImmutableBytesUsingUnchecked |  93.49 us | 1.859 us |  3.001 us |
|          BytesUsingUncheckedLinq | 483.25 us | 9.661 us | 23.147 us |
| ImmutableArrayUsingUncheckedLinq | 134.27 us | 2.679 us |  7.425 us |

https://github.com/planetarium/libplanet/blob/d998e4bcf52d98ba0f3b837cd0ea82d6bc026491/Libplanet/ByteUtil.cs#L107-L116

As seen in the result and a snippet from `ByteUtil.cs`, we are using pretty much the slowest possible method to compute a hash code for `byte[]`. This is probably due to an overhead of using `Linq` together with `byte[]` (and also something about `byte[]` not playing particularly nice with `Linq`). The implementation of `ByteUtil.CalculateHashCode()` should be updated to use a simple for loop as seen above instead of a `Linq` expression.

**Comment by sigridjineth** [comment]
I would assume the issue this :) #HacktoberFest
