### ISSUE TITLE
Evaluation order of transactions in a block

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#244]
Currently the evaluation order of transactions signed by multiple signers in a block are arbitrary and can be reoredered (fabricated) by a miner.  This indeterministic order makes games unfair.

For example, suppose there are two actions, *Attack* which decreases target's health and *Defend* which invalidates one succeeding *Attack* against on the signer.  *A* signs a transaction *t<sup>A</sup>* to *Attack* *B*, and *B* signs a transaction  *t<sup>B</sup>* to *Defend* itself.  If two transactions try to belong to a block, a block miner can determine whether to decrease *B*'s health or not.  If *t<sup>A</sup>* is followed by  *t<sup>B</sup>* *B* gets damage, whereas if *t<sup>B</sup>* is followed by  *t<sup>A</sup>* *A* loses its chance.

Therefore, the evaluation order of transactions in a block should not be determined by any certain party.

One idea I have is to make the evaluation order determined after a block is mined so that a miner can't deal with it:

 1. First of all, make `Block<T>.Mine()` to take a set of transactions instead of a sequence of transactions.  These transactions are unordered.
 2. When transactions (actions) in a block is being evaluated, sort them in the order of each one's *nonce*, which is derived from both a block hash and a transaction's signature.

This makes the order of evaluation impossible to predict until a block is mined.  The order is still arbitrary, but it makes game play in general more fair.

Any opinions are welcome.

**Comment by moreal** [comment]
I started to work on this issue :grin:

**Comment by moreal** [comment]
It's closed by #355.

**Comment by moreal** [comment]
In #355, I decided to order transactions by its nonce for hash. But it can cause undetermined hash, which also affects the order in which transactions are executed.
