### ISSUE TITLE
Refactor `GetBlockCommit()`

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#2550]
I think `GetBlockCommit(long index)` should work as the following:
- Retrieve the `Block<T>` of given `index`.
- If the retrieved `Block<T>` is a PoW block, return `null`.
- If the retrieved `Block<T>` is a PBFT block:
  - If `index == Tip.Index`, then return the `BlockCommit` cached.
  - If `index < Tip.Index`, then return the `Block<T>.LastCommit` of the next block.

**Comment by colibrishin** [comment]
I'll take this for focusing and continuing the `GetBlockCommit()` work context.

**Comment by colibrishin** [comment]
Closed by #2553
