### ISSUE TITLE
`currencyHash` format incorrect in `StateQuery<T>`?

### ISSUE THREAD

**Issue by tkiapril** [planetarium/libplanet#2656]
In https://github.com/planetarium/libplanet/blob/main/Libplanet.Explorer/Queries/StateQuery.cs#L105:
```csharp
string offsetBlockHash = context.GetArgument<string>("offsetBlockHash");
```
`offsetBlockHash` is retrieved as `string`. However, in https://github.com/planetarium/libplanet/blob/main/Libplanet.Explorer/Queries/StateQuery.cs#L47:
```csharp
byte[] currencyHashBytes = context.GetArgument<byte[]>(paramName);
```
`currencyHashBytes` is retrieved as `byte[]`. Because of this, in GraphQL query, if currencyHash is given as string:
```gql
query {
  stateQuery {
    totalSupply(currencyHash: "1bf0292d6dc5967e02b834fbe10c440dae0e2e6a", offsetBlockHash: "3a769844cb7b3095838532776cfd58f0f047d583129b29cfc3c1ecdd6792f4b7")
    {
      quantity
    }
  }
}
```
It seems like each character in the hex digest of currencyHash is converted into the ordinal of the each character and interpreted as such. The error message shows:
> "currencyHash must consist of 20 bytes.\nHashDigest<SHA1> must be 20 bytes, but 30 was given (Parameter 'hashDigest')"

I think this might be a bug. cc @dahlia

**Comment by dahlia** [comment]
I believe it behaves as we intended as [the parameter `currencyHash` is defined as `ByteStringType`.][1]  Note that `ByteStringType` is a custom graph type we defined, and [it interprets the given string as hexadecimal bytes.][2]  You could see the [test case][3] to ensure its behavior as well.

[1]: https://github.com/planetarium/libplanet/blob/f3100842dc32a1be58299371f970c10a9bfe0e99/Libplanet.Explorer/Queries/StateQuery.cs#L35
[2]: https://github.com/planetarium/libplanet/blob/f3100842dc32a1be58299371f970c10a9bfe0e99/Libplanet.Explorer/GraphTypes/ByteStringType.cs#L31-L32
[3]: https://github.com/planetarium/libplanet/blob/f3100842dc32a1be58299371f970c10a9bfe0e99/Libplanet.Explorer.Tests/Queries/StateQueryTest.cs#L113-L116
