### ISSUE TITLE
Trusted state synchronization on a restricted basis for faster IBD

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#272]
In principle, every single node should calculate their own states from the given transactions and actions from scratch, even though every node will eventually have the same deterministic states. Unlike transactions signatures, the only way to verify states in itself is to simply calculate transactions from scratch and compare them with the calculated result.  There's no way to digest the calculation in itself; calculating and verifying states cost the same.

The problem is that evaluating actions is hard to predict how long they will take.  As a rule of thumb, according to @longfin, validating actions (which requires evaluating them) take more than 10% of the time during receiving new blocks.

If a node wants to leverage states already calculated by peers it must trust them first.  However, blindly trusting peers makes the network fragile, because a malicious (or malfunctioning) node could send invalid states to peers.  Therefore if we're willing to trust some peers, it has to be allowed on only a restricted basis.

So I suggest an option to trust peers to use states calculated by them in a restricted-enough manner.  API-wise this would basically look like: the `Swarm` constructor has a new optional parameter named `trustedStateValidators`.  The type of this is a set of peers, i.e., `IImmutableSet<PublicKey>`.  Such a whitelist approach implements the <q>decentralized trust model</q> in the concept of [web of trust].  The basic idea is that a game player should decide what peers to trust, through a configuration file or, ideally, GUI.  Although each node could make some wrong decision on whom to trust, these mistakes do not impact on the entire network on a bigger scale.

There should be one more restriction on it IMHO: precalculated states should be leveraged only for [IBD].  If a node once catches up the topmost block of the major blockchain, a node should calculate states from the received transactions by itself.

Opinions?

[web of trust]: https://en.wikipedia.org/wiki/Web_of_trust
[IBD]: https://bitcoin.org/en/glossary/initial-block-download

**Comment by earlbread** [comment]
I agree with your suggestion.
It sounds good to have `trustedStateValidators` and use them only for IBD.

**Comment by longfin** [comment]
![image](https://user-images.githubusercontent.com/128436/58863446-d4f97480-86ed-11e9-8643-02c9a44aee53.png)
