### ISSUE TITLE
Make Swarm automatically broadcasts transactions

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#274]
Currently, a node must call `Swarm.BroadcastTx()` directly to introduce its own transaction. Sometimes, however, these requests can fail for a variety of reasons (e.g. network loss),  in current architecture, clients using Swarm should be responsible and request it again.

If `Swarm` can broadcast tx automatically for staged transactions, the client no longer has to assume this responsibility.

**Comment by earlbread** [comment]
Closed by #297.
