### ISSUE TITLE
`Currency`'s backward-compatibility was broken

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#3268]
Since [2.0.0](https://github.com/planetarium/libplanet/releases/tag/2.0.0), the `Currency` serialization's backward compatibility was broken. So `TxExecution`s created before 2.0.0, cannot be deserialized because their own Currencies cannot be deserialized.

<img width="1138" alt="image" src="https://github.com/planetarium/libplanet/assets/26626194/371ca38c-281c-4b44-9e9d-29d47366b346">

**Comment by riemannulus** [comment]
https://github.com/planetarium/libplanet/pull/3201/files#diff-4ba5d5e78e585f64e217441ed95e634f2d1b5c5df16ac3d419834d040882d7c4R677 May cause this PR.
