### ISSUE TITLE
Pre-study of applicability of BLS for Libplanet

### ISSUE THREAD

**Issue by OnedgeLee** [planetarium/libplanet#3603]
Though BLS is widely used(e.g., on Ethereum), benefits, disadvantages and difficulties for applying on the tendermint-style consensus was not carefully studied yet.
Before surveying how to apply it, checking applicability would be critical for our condition.

- [x] Surveying benefits, disadvantages, and difficultis for applying BLS on the Libplanet
- [x] If the benefit is ambiguous, perform benchmarks
- [x] Decide whether to use it or not, and how to use it to take full advantages

**Comment by OnedgeLee** [comment]
Signature verifying benchmark result (100 sigs)
```
DefaultCryptoBackend Verify : 118.4ms
NativeCryptoBackend Verify : 13.8ms
Herumi BLS FastAggregateVerify : 72.2ms
Herumi BLS AggregateVerify : 127.3ms
```

**Comment by riemannulus** [comment]
https://github.com/planetarium/libplanet/issues/3594#issuecomment-2008572918 Close.
