### ISSUE TITLE
Adjust 4.0 changes to other services

### ISSUE THREAD

**Issue by riemannulus** [planetarium/libplanet#3607]
Should consider those states.

- [x] AgentState
- [x] AvatarState
  - [x] AvatarState
  - [x] Inventory
  - [x] WorldInformation
  - [x] QuestList

Should consider those services.

- [x] DataProvider
- [x] Snapshot
- [x] Worldboss
- [x] IAP
- [x] MarketService
- [x] PatrolReward
- [x] Season pass

**Comment by OnedgeLee** [comment]
Current Status : 
- Updated `NineChronicles.RPC.Shared` to fix market service, but after that, client cannot be connected to headless.
- Season pass is not tested
- Monster collection is not tested
