### ISSUE TITLE
Settings are automatically added to settings.json when using vscode

### ISSUE THREAD

**Issue by s2quake** [planetarium/libplanet#3668]
I don't know why, but sometimes when I'm working on something, some settings are added to settings.json.
Also, some settings are deprecated or reformatted and are being used with incorrect values.
These issues show up as warnings in the Problems pane of vscode.
We will need to fix these issues in order to provide a more pleasant experience when working with vscode.
<img width="912" alt="image" src="https://github.com/planetarium/libplanet/assets/887680/6be34e35-3f12-4be3-a23a-0c91b8e0e0cb">

**Comment by riemannulus** [comment]
@Akamig Could you know about this?

**Comment by Akamig** [comment]
@riemannulus that file get created by user-specific VS Code configuration, so it's not per-se repository issue.

Separately from that we indeed have issue to replace deprecated Rome formatter to Biome.js or else.

**Comment by riemannulus** [comment]
> that file get created by user-specific VS Code configuration, so it's not per-se repository issue.

Ok, then you should ignore `settings.json` locally. `.git/info/exclude` is the one for that. @s2quake
