### ISSUE TITLE
Let's distinguish evaluating actions from executing actions

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#370]
We've used the both terms *evaluating* actions and *executing* actions in method names and docs and treated them compatible each other, but I've recently realized that when we say “executing actions” it could refer to one of these two meanings:

1. to calculate the resulting states of actions
2. to fill the storage with the resulting states that made by 1

So I suggest to distinguish *evaluating* actions from *executing* actions from now on, so that *evaluating* actions means only 1 above, and *executing* actions means only 2 above.

Request for comments!

**Comment by earlbread** [comment]
Sounds good to me. Actually, I was worried about setting the method names today.
