### ISSUE TITLE
Deterministic UUID (System.Guid) generator for distributed actions

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#371]
Since actions are executed in a distributed network, these have to be deterministic so that they have the same result regardless of node.  Therefore, we've provided APIs like [`IActionContext.Random`][1] to replace .NET's `System.Random`.  (Disclaimer: Saying random numbers should be deterministic here could sound contradictory, but it technically means “random numbers should be unpredictable until a block is mined, and they should not change and be consistent between all nodes in a distributed network after a block is once mined.”)

However, for UUIDs (`System.Guid` values) we currently provide no correspondence to `IActionContext.Random` for this.  Although library users could implement their own UUID generator built on `IActionContext.Random`, it's not only unhandy but also leads to make a mistake that a library user thoughtlessly use the `System.Guid.NewGuid()` method.

So I suggest to have an API to generate a `System.Guid` value in the same way `IActionContext.Random` generates a random number!

See also: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Guid.Unix.cs#L12-L35

[1]: https://docs.libplanet.io/0.4.1/api/Libplanet.Action.IActionContext.html#Libplanet_Action_IActionContext_Random

**Comment by ipdae** [comment]
i'll try this issue.
