### ISSUE TITLE
More precise logging at TurnClient.ProcessMessage()

### ISSUE THREAD

**Issue by limebell** [planetarium/libplanet#373]
Currently all exception during `TurnClient.ProcessMessage()` are logged as "An unexpected exception occured during parsing." The log message should contain more information of the exception.

**Comment by moreal** [comment]
Can you elaborate?

**Comment by riemannulus** [comment]
In my opinion. it is resolved by commit 24ab579.

**Comment by longfin** [comment]
> In my opinion. it is resolved by commit [24ab579](https://github.com/planetarium/libplanet/commit/24ab579aee1523689d914fec6216a167373fd5fc).

Right, it had solved by #476.
