### ISSUE TITLE
Remove redundant `Initialize()` on `TestUtils`

### ISSUE THREAD

**Issue by OnedgeLee** [planetarium/libplanet#3781]
## Context

https://github.com/planetarium/libplanet/blob/f3d6674a59cb00a961e67b68c8090d43de6dbc92/Libplanet.Tests/TestUtils.cs#L429-L442

Action `Initialize()` updates validator set of `IWorld` with given parameter `validatorSet`.
So above code, that iterates validatorSet, is redundant.
(**`Initialize()` only needs to be called once.**)

**Comment by hpatel292-seneca** [comment]
Hi @Atralupus, could you please assign this to me.

**Comment by Atralupus** [comment]
> Hi @Atralupus, could you please assign this to me.

Sure! I just assigned you to this issue.

And we're also running a hackathon right now named Modathon. We'd love for you to check it out 🙏🏻

https://nine-chronicles.dev/event/2024modathon

**Comment by hpatel292-seneca** [comment]
Hi @Atralupus, in the issue you mentioned about `that iterates validatorSet, is redundant.` , so you are saying to remove the iterator like this
```
var txs = transactions?.ToList() ?? new List<Transaction>();
long nonce = 0;
validatorSet = validatorSet ?? ValidatorSet;

// single transaction for the Initialize action, instead of iterating over validators.
txs.Add(
    Transaction.Create(
        nonce++,
        GenesisProposer,
        null,
        actions: new IAction[]
        {
            new Initialize(
                validatorSet: validatorSet,
                states: ImmutableDictionary.Create<Address, IValue>()),
        }.Select(x => x.PlainValue),
        timestamp: DateTimeOffset.MinValue));

```

**Comment by Atralupus** [comment]
> Hi @Atralupus, in the issue you mentioned about `that iterates validatorSet, is redundant.` , so you are saying to remove the iterator like this
> 
> ```
> var txs = transactions?.ToList() ?? new List<Transaction>();
> long nonce = 0;
> validatorSet = validatorSet ?? ValidatorSet;
> 
> // single transaction for the Initialize action, instead of iterating over validators.
> txs.Add(
>     Transaction.Create(
>         nonce++,
>         GenesisProposer,
>         null,
>         actions: new IAction[]
>         {
>             new Initialize(
>                 validatorSet: validatorSet,
>                 states: ImmutableDictionary.Create<Address, IValue>()),
>         }.Select(x => x.PlainValue),
>         timestamp: DateTimeOffset.MinValue));
> ```

Looks great! Please submit a PR, and we’ll review it with the team. Thanks, and happy contributing!
