### ISSUE TITLE
Libplanet.Tests.Net.SwarmTest.WorksAsExpected() occasionally fails.

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#38]
[Error Log](https://dev.azure.com/planetarium-dev/libplanet.net/_build/results?buildId=177&view=logs&jobId=595d1c2d-d086-5383-90dd-774a3639c562&taskId=fba3dbb4-4ddb-5445-33b5-a73b8ae1de38&lineStart=227&lineEnd=228&colStart=1&colEnd=1)

**Comment by longfin** [comment]
[another case](https://dev.azure.com/planetarium-dev/libplanet.net/_build/results?buildId=210).

**Comment by dahlia** [comment]
Although it's not `SwarmTest.WorksAsExpected()` but `SwarmTest.CanGetBlock`, it seems relevant: <https://dev.azure.com/planetarium-dev/libplanet.net/_build/results?buildId=239&view=ms.vss-test-web.build-test-results-tab>.
