### ISSUE TITLE
Remove unnecessary file

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#3979]
## Context

The repository contains a file that looks like the build result of vitest.config.ts. This doesn't affect the build and shouldn't be there, so it's probably a good idea to remove it to avoid confusion.

https://github.com/planetarium/libplanet/blob/c1a1c5e2e377b147dc96e7dc480bca3481c41a99/%40planetarium/account-web3-secret-storage/vitest.config.ts.timestamp-1681276750671.mjs

**Comment by violet-ewgd** [comment]
Your meaning is that need to delete the file vitest.config.ts.timestamp-1681276750671.mjs from the repository, right?

**Comment by moreal** [comment]
> Your meaning is that need to delete the file vitest.config.ts.timestamp-1681276750671.mjs from the repository, right?

Hello @violet-ewgd. You're right

**Comment by moreal** [comment]
Resolved by https://github.com/planetarium/libplanet/pull/3980
