### ISSUE TITLE
Make FindNextHashesChunkSize configurable

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet#407]
The internal property `BlockChain<T>.FindNextHashesChunkSize` made to test `BlockDownloadState` in `Swarm<T>.PreloadAsync()`. But it is hard to understand the purpose of the property and not configurable. So it would be better to make it configurable in `Swarm<T>`.

**Comment by longfin** [comment]
Can we treat this as 'good first issue'?

**Comment by kanghyojun** [comment]
I'm working on it.
