### ISSUE TITLE
Single node configuration for development environment

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#42]
Currently, the only way to correctly generate a block is to call `Blockchain.MineBlock()` to mine block. However, in a development environment that typically consists of a single node, mining has a large variation in resource usage, making it difficult to guarantee the block creation time. it sometimes makes development and testing difficult.

So for a development or test chain, we need a method (e.g. configuration) that allows us to create a valid block without these mining processes.

**Comment by dahlia** [comment]
I think we can now achieve this by implementing a custom `IBlockPolicy<T>`.  Or do we need a kind of façade (which implements `IBlockPolicy<T>`) for single node?
