### ISSUE TITLE
Ignore BlockHashes or TxIds which already stored

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#461]
By current implementation, when `Swarm<T>` received `TxIds` or `BlockHashes` from other peers, it will try to receive payload even if it already has that transaction or block.

**Comment by limebell** [comment]
I think `Swarm<T>` now ignores `TxIds` which are staged. Do you mean by the transactions that are already contained in blocks?

**Comment by longfin** [comment]
> I think `Swarm<T>` now ignores `TxIds` which are staged. Do you mean by the transactions that are already contained in blocks?

Nope, I've missed that `Swarm<T>.ProcessTxIds()` already ignores `TxIds` which are staged. 

but `Swarm<T>.ProcessBlockHashes` is still trying to receive without check. so we should fix it as like as `ProcessTxIds()`
