### ISSUE TITLE
Rename IStore.IterateIndex to IStore.IterateIndexes

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#462]
Context:

> [how about keep `ForkIndexes()` in this PR and rename `IterateIndex()` to `IterateIndexes()` in other PR?](https://github.com/planetarium/libplanet/pull/420#discussion_r317906534)

**Comment by dahlia** [comment]
I believe the link is incorrect.

**Comment by longfin** [comment]
> I believe the link is incorrect.

Fixed.

**Comment by limebell** [comment]
closed by #560
