### ISSUE TITLE
On .NET Framework + Windows build some test cases seem missing

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#478]
<https://dev.azure.com/planetarium/libplanet/_build/results?buildId=1376>

The above build was invoked by a commit which made `SwarmTest.PreloadAsyncCancellation()` test to fail so that it prints logs.  All tests had to fail, but tests on .NET Framework + Windows passed.  I guess some test cases don't run on .NET Framework + Windows.

---

FYI the commit was:

```diff
commit 0cd8241c0b240d7d941caccc4b55bca31ba66046
Author: Hong Minhee <hong.minhee@gmail.com>
Date:   2019-08-29 22:36:15 +0900

    LOG

diff --git a/Libplanet.Tests/Net/SwarmTest.cs b/Libplanet.Tests/Net/SwarmTest.cs
index adc84c95..43583cef 100644
--- a/Libplanet.Tests/Net/SwarmTest.cs
+++ b/Libplanet.Tests/Net/SwarmTest.cs
@@ -1284,6 +1284,9 @@ namespace Libplanet.Tests.Net
                     receiverChain.GetStates(new[] { address })[address]
                 );
             }
+
+            // FIXME: Intentionally make it fails so that it prints out logs
+            Assert.Null(minerChain.Tip);
         }
 
         private async Task<Task> StartAsync(
```

**Comment by earlbread** [comment]
In the build, 225 tests are executed on Windows NET Framework while 239 tests are executed on the other platforms. I think the tests using `InlineData` are not executed on the Windows NET Framework because the number of tests using `InlineData` is 14(239-225=14).
