### ISSUE TITLE
Remove duplicated code which checks difficulty

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#502]
In my thought, it isn't needed to check that the difficulty is 0 in `Hashcash.Answer(Stamp, long)`, because `HashDigest<SHA256>.Satisfies(long)` checks it enough.

see these lines, [Libplanet/HashDigest.cs#L149](https://github.com/planetarium/libplanet/blob/d6301aface1eccd37c3de7c7b1bef5dc6398918d/Libplanet/HashDigest.cs#L149), [Libplanet/Hashcash.cs#L57](https://github.com/planetarium/libplanet/blob/d6301aface1eccd37c3de7c7b1bef5dc6398918d/Libplanet/Hashcash.cs#L57)

**Comment by RozzaysRed** [comment]
Sorry about the duplicate pr...totally just destroyed the first PR with not setting up the git properly on the machine I'm on.  Hopefully this will be better.

**Comment by moreal** [comment]
It's closed by #536
