### ISSUE TITLE
ChainIdNotFoundException occurs during LiteDBStore.ForkStateReferences<T>

### ISSUE THREAD

**Issue by limebell** [planetarium/libplanet#509]
When trustedPeer option is set to be empty during `Swarm<T>.PreloadAsync`, this seems to be occurred.

**Comment by limebell** [comment]
It seems like trustedPeer option is not related.

**Comment by limebell** [comment]
This seems to be occurred when execute `Fork` where StateReferences are empty.

**Comment by dahlia** [comment]
This seems due to the patch #467 which removed the `addressesToStrip` parameter from `IStore.ForkStateReferences()` method.
