### ISSUE TITLE
Turn BlockChain<T>.GetStates() into GetState()

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#510]
As it seems rare to look up multiple states at a time, and dealing with multiple addresses makes the implementation of `BlockChain<T>.GetStates()` complicated, I suggest to turn `GetStates()` into `GetState()` which takes only one `Address` at a call instead of `IEnumerable<Address>`.

**Comment by qtuu** [comment]
I would like to give this a try.

**Comment by moreal** [comment]
This is resolved by #563.
