### ISSUE TITLE
Restrict allowed types for actions ands states

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#541]
Currently we serialize `IAction` objects into `IImmutableDictionary<string, object>` values and states into `object`s.  The difficult part of this behavior is that it brings .NET's serialization mechanism which requires the equivalent runtime types between serialization and deserialization time.  It makes difficult to share and interpret the same blockchain between different apps, like the older version and newer version of the same app or a game and Libplanet Explorer.

So I suggest to get rid of these `object` things and use a more stricter interface in the same way JSON only accepts few primitive types (null, Boolean, number, string, array, string-keyed dictionary).

Relevant code:

- `IAction.PlainValue` property
- `IAction.LoadPlainValue()` method
- `IAccountStateDelta.GetState()` method
- `IAccountStateDelta.SetState()` method
- `BlockChain<T>.GetStates()` method
- `AccountStateGetter` delegate
- `AddressStateMap` class → I believe this should be gone (#98).

See also Bencodex's `IValue` interface.

**Comment by limebell** [comment]
I guess this issue is resolved by #552.

**Comment by moreal** [comment]
In my thought, it was completed by the issues, #552 and #692.
