### ISSUE TITLE
Rename “maxValue” parameters in IRandom.Next() methods

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#555]
The `IRandom.Next(int minValue, int maxValue)` and `IRandom.Next(int maxValue)` methods never return `maxValue` but only values less than it.  So the word “max” could mislead users.  I suggest to find a more concise word to indicate that a number is chosen in a *half-open* interval.

**Comment by pBouillon** [comment]
Hi ! May I take this issue ? I would suggest `IRandom.Next(int lowerBound, int upperBound)` (along with a propper XML documentation)

**Comment by dahlia** [comment]
Names you suggested seems good.

**Comment by pBouillon** [comment]
Awesome !
I'm on it then !
