### ISSUE TITLE
Submit Libplanet to Unity Asset Store

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#60]
As our primary target platform is Unity, and Unity currently does not treat NuGet as a first-class citizen, we should pack Libplanet as a [Unity asset package][1] and submit it to [Unity Asset Store].  Ideally, it should be automatically submitted to Unity Asset Store every time we pushed a tag to the repository, in the similar way to NuGet (see also #52).  First of all, we need some survey about:

- [ ] legal compatibility between our license and the [terms and EULA of Unity Asset Store][2]
- [ ] non-interactive way (i.e., non-GUI but CLI) to pack a Unity asset package
- [ ] programmable way (API or CLI) to submit asset packages to Unity Asset Store

[1]: https://docs.unity3d.com/2019.1/Documentation/Manual/AssetPackages.html
[Unity Asset Store]: https://assetstore.unity.com/
[2]: https://unity3d.com/legal/as_terms

**Comment by longfin** [comment]
Related projects

- https://github.com/Lachee/Unity-Package-Exporter (CLI exporter)
- https://github.com/Lachee/discord-rpc-csharp (example)

**Comment by dahlia** [comment]
See also this article: [Using CircleCI to build/test/make unitypackage on Unity](https://medium.com/@neuecc/using-circle-ci-to-build-test-make-unitypackage-on-unity-9f9fa2b3adfd) by Yoshifumi Kawai, the author of UniRx.

**Comment by dahlia** [comment]
According to the Unity's official [*Submission Guidelines*][1] (1.1.1.b):

> The compatible licenses that we mainly allow are MIT, BSD 3-Clause, and Apache. Any licenses that require a product to maintain open-sourced or limit usability in commercial products such as GNU/GPL Mozilla Public License, or any Creative Commons that requires attribution will not be allowed.

[1]: https://unity3d.com/asset-store/sell-assets/submission-guidelines
