### ISSUE TITLE
Add IStore.Contains(HashDigest<SHA256>)

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#615]
In the current `IStore` API, we must fetch the whole block to determine that exists. ([i.e.](https://github.com/planetarium/libplanet/blob/6be0dc8/Libplanet/Store/BlockSet.cs#L68)).
But, if there is an API checking block existence by only a block's hash(`HashDigest<SHA256>`), we can skip block fetching.

**Comment by yoojin2088** [comment]
i work on it

**Comment by limebell** [comment]
Closed by #678
