### ISSUE TITLE
Swarm<T>'s events should be internal

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#705]
Currently, some exposed public events in `Swarm<T>` (i.e. `TxReceived`, `BlockReceived`) can be used from anyone. But it's to allow you to control the part of the low level logic. So they should be hidden from users by being `private` or `internal`. But in unit test, they are needed to access. Therefore, IMO they should be, `internal`.

**Comment by Oaroomy** [comment]
I'm going to work on this.

**Comment by moreal** [comment]
I believe it's resolved by #725.
