### ISSUE TITLE
Libplanet.Stun.Tests's tests' namespaces are incorrect

### ISSUE THREAD

**Issue by limebell** [planetarium/libplanet#729]
It should be `Libplanet.Stun.Tests.Stun` + a, but `Stun` is missing. Or, just remove `Stun` folder I guess.

**Comment by riemannulus** [comment]
This issues seems resolved by commit f342613.

**Comment by longfin** [comment]
> This issues seems resolved by commit [f342613](https://github.com/planetarium/libplanet/commit/f3426133bfbe46017f89b00f8405eb9cc74f5e20).

You're right. it had solved by #315.
