### ISSUE TITLE
Make BlockTest.EvaluateActionsPerTx() work deterministic

### ISSUE THREAD

**Issue by limebell** [planetarium/libplanet#754]
In a block, order of transaction to be executed is determined by its id. Since id is generated by its payload, user cannot predict the order of execution.
In `BlockTest.EvaluateActionsPerTx()` test, two transactions are put in a block. The test is designed for the specific order of transaction execution order, so it will be great to generate transactions randomly and cover all cases.

**Comment by riemannulus** [comment]
Using random transactions to identify all cases would rather create non-deterministic tests. Therefore, we will proceed towards solidifying the test by adding more test cases.
