### ISSUE TITLE
Would TxId be better if it inherits HashDigest<SHA256>?

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#79]
Since `TxId` is a SHA-256 digest, the most of things are in common with `HashDigest<SHA256>`.  Would `TxId` be better to inherit `HashDigest<256>`?  Or, rather, would it be fine even if we get rid of `TxId` at all and replace them with `HashDigest<256>`?

**Comment by longfin** [comment]
I think considering `TxId`  as `HashDigest<SHA256>` makes sense. but it also means that we allow to assign `TxId` to any `HashDigest<SHA256>` fields (e.g. `Block.Hash`). it can be quite fragile.

So, I suggest to make some other concrete type for these type like `BlockHash` to distinguish among them if we want to use inheritance.

**Comment by dahlia** [comment]
Having a distinct type for each `BlockHash` and `TxId` and they inheriting `HashDigest<SHA256>` seems good.

**Comment by qria** [comment]
I call dibs on this issue

**Comment by qria** [comment]
`HashDigest<T>` was a `struct` not `class` so inheritance is not possible. what do?

**Comment by dahlia** [comment]
@qria You're right.  The idea in itself seems invalid.

**Comment by qria** [comment]
I no longer am working on this until there's a new idea for this.

**Comment by longfin** [comment]
I'll close this issue until we have a new idea to address this issue.
