### ISSUE TITLE
Make HashDigest<SHA256> serializable

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#795]
Its' continued from #99. `HashDigest<SHA256>` isn't `[Serializable]` yet.

**Comment by dahlia** [comment]
Does .NET serialization mechanism allow immutable values serialized and deserialized?

**Comment by longfin** [comment]
> Does .NET serialization mechanism allow immutable values serialized and deserialized?

I guess marking `[Serializable]` to `HashDigest<SHA256>` is possible like #124.

**Comment by longfin** [comment]
Resolved by #1125
