### ISSUE TITLE
Add the genesis hash to Transaction<T>

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#796]
In order to prevent inapplicable transactions (made for a different network) polluting the network, I suggest to add `Transaction<T>.GenesisHash` property.

**Comment by dahlia** [comment]
(See also the [discussion][1] from the Discord in Korean.)

There is a corner case where transactions belonging to a genesis block cannot determine its belonging genesis block hash.  [Two ways to solve this][2]:

1. `Transaction<T>.GenesisHash` be optional (i.e., `HashDigest<SHA256>?` instead of `HashDigest<SHA256>`), and if and only if a transaction belongs to a genesis block the field can be `null`.
2. Disallow genesis blocks to have any transactions.

Personally I prefer the first way.  Any ideas?  /cc @planetarium/libplanet @limebell 

[1]: https://discordapp.com/channels/539405872346955788/546978081743699968/710729338827571252
[2]: https://discordapp.com/channels/539405872346955788/546978081743699968/711470513066737714

**Comment by limebell** [comment]
Since genesis block may contain initial data, first way looks better to me too. I'll try to work on this issue based on this idea.
