### ISSUE TITLE
Fix broken docs style: the footer overlays on the left sidebar

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#819]
![](https://user-images.githubusercontent.com/12431/76397605-ba5fd480-63be-11ea-8daf-828fdb863f2f.png)

When the content does not length the footer overlays on the left sidebar.

**Comment by limebell** [comment]
Which browser you are using? In the case of chrome, footer is not shown if the content's length is not enough. (maybe it is a bug too?)

![image](https://user-images.githubusercontent.com/5073795/76823959-fc729580-6858-11ea-9691-f764aceca1b4.png)

**Comment by dahlia** [comment]
I used Firefox.  Indeed, in Chrome the footer seems disappeared at all. 🤔

**Comment by limebell** [comment]
Well I installed Firefox and tried on it, it still not shown 🤔. Maybe this depends on OS instead of browser?

**Comment by dahlia** [comment]
Hmm… I still can reproduce this on my Firefox (75.0b2). Note that I am using the beta channel (not the stable channel).

**Comment by longfin** [comment]
It can be produced in my box as below. (Windows 10 Pro, FF 73.0)

![image](https://user-images.githubusercontent.com/128436/76824720-51afa680-685b-11ea-9070-026a70538cd9.png)

but when I resize the window, it was corrected.

![image](https://user-images.githubusercontent.com/128436/76824806-98050580-685b-11ea-8809-fd590a206776.png)

**Comment by limebell** [comment]
I found that resolution of my laptop was the problem. I can reproduce footer overlay problem both on Chrome and Firefox 😀. I'll take a look at this issue.
