### ISSUE TITLE
Versioning action classes

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#904]
Libplanet's "action"s(implementations of `IAction`) are tagged by `Libplanet.Action.ActionType` attribute for serialization. but sometime, some "action"s perform different actions as they are upgraded, and the serialization format is different for this. at this time, if the serialization type of an action tagged with the `ActionType` is changed, serialization and deserialization may fail.

The simplest way to avoid this is to specify a new `ActionType` each time.(e.g. `ActionType("hack_and_slash_v13")`. but If we provide dedicated primitives(e.g. `Version(13)`) for specifying the version, we might be able to distinguish it more meaningfully. 

Furthermore, it may be possible to store bytecode(CIL) according to the version if necessary.

**Comment by longfin** [comment]
Versioning can help serializing & execution on various versions of actions. but it can't help if target action relies on other classes and game dev also updates it. In this case, we should versioning all of them. :confused:

To handle this problem well, maybe you need .NET assembly level versioning, not action class level versioning. The .NET ecosystem seems to support tools like `AppDomain`(pre .NET Core) or `AssemblyLoaderContext`(.NET Core 3+) for isolated loading of assemblies.

**Comment by dahlia** [comment]
> Libplanet's "action"s(implementations of `IAction`) are tagged by `Libplanet.Action.ActionType` attribute for serialization.

In this topic, you mean only `PolymorphicAction<T>`, not the whole `IAction<T>`, right?

**Comment by longfin** [comment]
> In this topic, you mean only `PolymorphicAction<T>`, not the whole `IAction<T>`, right?

Right, I've confused.

**Comment by longfin** [comment]
> > In this topic, you mean only `PolymorphicAction<T>`, not the whole `IAction<T>`, right?
> 
> Right, I've confused.

But, I also believe all actions including not `PolymorphicAction<T>` need versioning feature as migration mechanism too.
