### ISSUE TITLE
✊🏿 Let's rename the master branch → main

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#938]
For the rationale, please read the following discussion and article:

- <https://lore.kernel.org/git/CAOAHyQwyXC1Z3v7BZAC+Bq6JBaM7FvBenA-1fcqeDV==apdWDg@mail.gmail.com/>
- <https://www.bbc.com/news/technology-53050955>

For the how-to, GitHub officially provides the following guide:

<https://github.com/github/renaming>

**Comment by riemannulus** [comment]
Github say they investing migration tools and it finish until later this year. https://github.com/github/renaming#now-supporting-early-movers-
I think we're ok to wait until investing done.

**Comment by dahlia** [comment]
IMHO we don't need any special migration tools to do this.  Instead, I believe we can achieve this by doing the following things:

1. Replace hard-coded `master` strings with `main` in shell scripts and build scripts (mostly YAML) under *.github/* and *.azure-pipelines/* directories.
2. Push the above changes to the new branch named *main*.
3. Apply the same branch protection rules with the *master* to the *main*.

    ![](https://user-images.githubusercontent.com/12431/89118385-5a3e0c00-d4e0-11ea-9353-e5bb8e769d31.png)

4. Change the default branch name to the *main* of this GitHub repository.

    ![](https://user-images.githubusercontent.com/12431/89118366-2fec4e80-d4e0-11ea-8c59-333016c894a1.png)

This would change mostly nothing on our existing workflow, because we already haven't used touch the *master* branch by hand, but only through merging pull requests.

**Comment by dahlia** [comment]
@riemannulus made it! e687b8d542e2c4bf9c60bd33505c52c1f01f0473 ✊🏿👍🏼
