### ISSUE TITLE
Swarm.Running property's getter throws NullReferenceException

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#97]
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Libplanet.Net.Swarm.get_Running () [0x00000] in <6251e25246f14915a1ae0ecbd6356d72>:0 
  at Libplanet.Net.Swarm.Finalize () [0x00000] in <6251e25246f14915a1ae0ecbd6356d72>:0 
```
https://dev.azure.com/planetarium-dev/libplanet.net/_build/results?buildId=378

**Comment by longfin** [comment]
It seems to occur only in #88. I'll handle it together.

**Comment by dahlia** [comment]
I tried twice to reproduce this on the current master (58d615d89bbf20e6613078cceccb8d2b26651ff1), but failed.  I did the same thing twice on #88 (91e3cfea27b96213918137abdb8fd9d2e8c0c90c), and it's reproduced on both tries.

**Comment by longfin** [comment]
I guess this has been completed due to https://github.com/longfin/libplanet.net/commit/1a664c16ac5d30bdd8a56834d407a2d9a85428c9. If it occurs again, please reopen it.
