### ISSUE TITLE
Replace AddressStateMap with IImmutableDictionary<Address, object>

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#98]
The current implementation of `AddressStateMap` is just a thin wrapper around `ImmutableDictionary<Address, object>`, and implements `IImmutableDictionary<Address, object>` as well at a time.  This was intended to mimic `typedef IImmutableDictionary<Address, object> AddresStateMap;` in C#. (Although C# allows `using AddresStateMap = IImmutable<Address, object>;`, the alias is scoped to only a file.)  However, as `AddressStateMap` is not completely equivalent to `IImmutableDictionary<Address, object>` but only a subtype of it, it tends to cast things up and down, which leads runtime type unsafety.  For instance, when we implement a `IAction.Execute()` method, it looks like:

```c#
public AddressStateMap Execute(IActionContext context)
{
    AddressStateMap states = context.PreviousStates;
    IImmutableDictionary<Address, object> newStates =
        states.SetItem(context.To, "new value");
    return (AddressStateMap) newStates;  // downcast
}
```

If we completely replace `AddressStateMap` with `IImmutableDictionary<Address, object>` it would look like instead:

```c#
public AddressStateMap Execute(IActionContext context)
{
    IImmutableDictionary<Address, object> states = context.PreviousStates;
    IImmutableDictionary<Address, object> newStates =
        states.SetItem(context.To, "new value");
    return newStates;  // no cast
}
```

**Comment by longfin** [comment]
@dahlia Is this still a valid issue?

**Comment by dahlia** [comment]
Yes, it is still valid in some degree, but the ideas I suggested above are now unnecessary anymore for the most part.  I am going to make a patch to completely close this issue soon!
