### ISSUE TITLE
Backspace not working when create key in CLI.

### ISSUE THREAD

**Issue by Hazealign** [planetarium/libplanet#983]
# Issue
 - When Using Libplanet.Tools, Backspace not working in input passphrase.
 - Only Works Well in Windows.

# Testing Environment
 - WSL2 Ubuntu 18.04 in Windows 10 2004
 - macOS 10.15

**Comment by Hazealign** [comment]
This Project using [GetPass](https://github.com/alefranz/GetPass), but I created Sample Project. It works well in Every Environment.

```
using System;
using GetPass;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            var password = ConsolePasswordReader.Read();
            Console.Write(password);
            Console.WriteLine();
        }
    }
}
```

**Comment by dahlia** [comment]
Thank you for reporting!

I guess this happens because `GetPass` does synchronous I/O whereas the entire `planet` runs on `async` mode… 🤔
