### ISSUE TITLE
Make bytes wrapper struct serializable.

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#99]
Currently, bytes wrapper structs (e.g. `Address`, `TxId`) can't be serializable in .NET manner due to lacking [`[Serializable]` ](https://docs.microsoft.com/en-US/dotnet/api/system.serializableattribute?view=netstandard-2.0) attribute. so the following actions are required.

1. Should attach `[Serializable]` attributes to target structs.
2. Should implement [`ISerializable`](https://docs.microsoft.com/en-US/dotnet/api/system.runtime.serialization.iserializable?view=netstandard-2.0) properly.

**Comment by qria** [comment]
I'll take a stab at this
